
export type BobotItem = {
  jenis_order_name: string;
  order_type?: string;
  bobot: number;
  sla_hour?: number;
  teknisi_ideal?: number;
};

export const productivityWeights: Record<string, BobotItem[]> = {
  "ASSURANCE B2B EXTERNAL": [
    { jenis_order_name: "Aktivasi Cross Connect TDE", bobot: 4 },
    { jenis_order_name: "Aktivasi/Migrasi/Dismantel DCS", bobot: 4 },
    { jenis_order_name: "Aktivasi/Migrasi/Dismantel Digiserve", bobot: 4 },
    { jenis_order_name: "Corrective Akses Tower CENTRATAMA", bobot: 4 },
    { jenis_order_name: "Corrective Akses Tower Lintasarta", bobot: 4 },
    { jenis_order_name: "Corrective Akses Tower UMT", bobot: 4 },
    { jenis_order_name: "Corrective Cross Connect TDE", bobot: 4 },
    { jenis_order_name: "Corrective CSA", bobot: 4 },
    { jenis_order_name: "Corrective Digiserve", bobot: 4 },
    { jenis_order_name: "Corrective MMP", bobot: 4 },
    { jenis_order_name: "Corrective MyRep", bobot: 2 },
    { jenis_order_name: "Corrective NuTech", bobot: 4 },
    { jenis_order_name: "Corrective SNT", bobot: 4 },
    { jenis_order_name: "Corrective SPBU", bobot: 4 },
    { jenis_order_name: "Corrective TBG", bobot: 4 },
    { jenis_order_name: "Corrective Tower POLARIS", bobot: 4 },
    { jenis_order_name: "Corrective Tower TIS", bobot: 4 },
    { jenis_order_name: "Inventory SPBU", bobot: 4 },
    { jenis_order_name: "Preventif MMP", bobot: 2 },
    { jenis_order_name: "Preventive Akses Tower CENTRATAMA", bobot: 8 },
    { jenis_order_name: "Preventive Akses Tower Lintasarta", bobot: 2 },
    { jenis_order_name: "Preventive Akses Tower UMT", bobot: 2 },
    { jenis_order_name: "Preventive Asianet", bobot: 2 },
    { jenis_order_name: "Preventive CSA", bobot: 2 },
    { jenis_order_name: "Preventive NuTech", bobot: 4 },
    { jenis_order_name: "Preventive SPBU", bobot: 8 },
    { jenis_order_name: "Preventive TBG", bobot: 2 },
    { jenis_order_name: "Preventive Tower POLARIS", bobot: 2 },
    { jenis_order_name: "Preventive Tower TIS", bobot: 2 },
    { jenis_order_name: "Relokasi DCS", bobot: 1 },
    { jenis_order_name: "Relokasi Digiserve", bobot: 1 },
    { jenis_order_name: "Preventive FIberisasi", bobot: 2 }, // Typo from image: Flberisasi -> FIberisasi
    { jenis_order_name: "SPPG", bobot: 8, sla_hour: 8 },
    { jenis_order_name: "Corrective IBU - FTTR", bobot: 5 },
    { jenis_order_name: "Corrective Surge", bobot: 4 },
    { jenis_order_name: "Preventive MS SNT", bobot: 2 },
    { jenis_order_name: "MS IT & FO_SJU", order_type: "CORRECTIVE", bobot: 5 },
    { jenis_order_name: "MS IT & FO_SJU", order_type: "PREVENTIF", bobot: 5 },
    { jenis_order_name: "MS PATROLI_Telin", order_type: "CORRECTIVE", bobot: 4 },
    { jenis_order_name: "MS PATROLI_Telin", order_type: "PREVENTIF", bobot: 4 },
    { jenis_order_name: "Corrective Asianet", bobot: 4 },
  ],
  "ASSURANCE B2B INTERNAL": [
    { jenis_order_name: "HSI Indihome Reseller", bobot: 2, sla_hour: 36 },
    { jenis_order_name: "Tangible", bobot: 1 },
    { jenis_order_name: "Tiket Datin Kategori 1", bobot: 2.67, sla_hour: 1.5 },
    { jenis_order_name: "Tiket Datin Kategori 2", bobot: 2.67, sla_hour: 3.6 },
    { jenis_order_name: "Tiket Datin Kategori 3", bobot: 2.67, sla_hour: 7.2 },
    { jenis_order_name: "Tiket HSI Indibiz", bobot: 2, sla_hour: 24 },
    { jenis_order_name: "Tiket NodeB CNQ (Preventive/Quality)", bobot: 4, sla_hour: 4 },
    { jenis_order_name: "Tiket NodeB Critical", bobot: 6, sla_hour: 4 },
    { jenis_order_name: "Tiket NodeB Low", bobot: 4, sla_hour: 24 },
    { jenis_order_name: "Tiket NodeB Major", bobot: 4, sla_hour: 8 },
    { jenis_order_name: "Tiket NodeB Minor", bobot: 4, sla_hour: 16 },
    { jenis_order_name: "Tiket NodeB Premium", bobot: 6, sla_hour: 2 },
    { jenis_order_name: "Tiket NodeB Premium Preventive", bobot: 4, sla_hour: 48 },
    { jenis_order_name: "Tiket OLO Datin Gamas", bobot: 4, sla_hour: 7 },
    { jenis_order_name: "Tiket OLO Datin Non Gamas", bobot: 4, sla_hour: 4 },
    { jenis_order_name: "Tiket OLO Datin Quality", bobot: 4, sla_hour: 7 },
    { jenis_order_name: "Tiket OLO SL WDM", bobot: 4, sla_hour: 6 },
    { jenis_order_name: "Tiket OLO SL WDM Quality", bobot: 4, sla_hour: 7 },
    { jenis_order_name: "Tiket Pra SQM Gaul HSI", bobot: 2 },
    { jenis_order_name: "Tiket SIP Trunk", bobot: 2.67, sla_hour: 10 },
    { jenis_order_name: "Tiket SQM Datin", bobot: 2.67 },
    { jenis_order_name: "Tiket SQM HSI", bobot: 2 },
    { jenis_order_name: "Tiket WIFI ID", bobot: 2.67, sla_hour: 24 },
    { jenis_order_name: "Tiket Wifi Logic", bobot: 2.67, sla_hour: 6 },
    { jenis_order_name: "Unspec DATIN", bobot: 2.67 },
    { jenis_order_name: "Unspec HSI", bobot: 2 },
    { jenis_order_name: "Unspec SITE", bobot: 0 },
    { jenis_order_name: "Unspec WIFI", bobot: 0 },
    { jenis_order_name: "Validasi Data EBIS", bobot: 0 },
    { jenis_order_name: "Validasi Data WIFI", bobot: 0 },
    { jenis_order_name: "Survey Sewa Tiang", bobot: 0 },
  ],
  "ASSURANCE B2C": [
    { jenis_order_name: "Dismantling DC", bobot: 1 },
    { jenis_order_name: "Infracare", bobot: 2 },
    { jenis_order_name: "Lapsung (Laporan Langsung)", bobot: 2, sla_hour: 36 },
    { jenis_order_name: "SQM Reguler", order_type: "Workhours", bobot: 2, sla_hour: 4 },
    { jenis_order_name: "SQM Reguler", order_type: "NonWorkhours", bobot: 2 },
    { jenis_order_name: "Tangible ODP", bobot: 2 },
    { jenis_order_name: "Tiket GAMAS", order_type: "DISTRIBUSI", bobot: 4, teknisi_ideal: 3 },
    { jenis_order_name: "Tiket GAMAS", order_type: "FEEDER", bobot: 10, teknisi_ideal: 4 },
    { jenis_order_name: "Tiket GAMAS", order_type: "ODC", bobot: 18, teknisi_ideal: 6 },
    { jenis_order_name: "Tiket GAMAS", order_type: "ODP", bobot: 3, teknisi_ideal: 2 },
    { jenis_order_name: "Tiket Reguler", order_type: "Platinum", bobot: 2, sla_hour: 6 },
    { jenis_order_name: "Tiket Reguler", order_type: "Diamond", bobot: 2, sla_hour: 3 },
    { jenis_order_name: "Tiket Reguler", order_type: "VVIP", bobot: 2, sla_hour: 3 },
    { jenis_order_name: "Tiket Reguler", order_type: "Gold", bobot: 2, sla_hour: 12 },
    { jenis_order_name: "Tiket Reguler", order_type: "Reguler", bobot: 2, sla_hour: 36 },
    { jenis_order_name: "Tiket Reguler", order_type: "HVC_Platinum", bobot: 2, sla_hour: 6 },
    { jenis_order_name: "Tiket Reguler", order_type: "HVC_Gold", bobot: 2, sla_hour: 12 },
    { jenis_order_name: "Tiket Reguler", order_type: "HVC_Diamond", bobot: 2, sla_hour: 3 },
    { jenis_order_name: "Tiket Reguler", order_type: "NonHVC", bobot: 2, sla_hour: 36 },
    { jenis_order_name: "Unspec Reguler", bobot: 2 },
  ],
  "PROVISIONING B2B EKSTERNAL": [
    { jenis_order_name: "Provisioning MyRep", order_type: "PSB", bobot: 2 },
    { jenis_order_name: "PSB Surge", bobot: 4 },
    { jenis_order_name: "Provisioning 5 Menara Bintang", order_type: "PSB", bobot: 8 },
    { jenis_order_name: "PSB IBU - FTTR", bobot: 5 },
    { jenis_order_name: "PT Anagata Cipta Teknologi (KerjainAja)", bobot: 8 },
    { jenis_order_name: "PSB TBG", order_type: "PSB", bobot: 2 },
    { jenis_order_name: "Provisioning Hypernet", order_type: "PSB", bobot: 2 },
  ],
  "PROVISIONING B2B INTERNAL": [
    { jenis_order_name: "PSB DATIN", bobot: 6.4, sla_hour: 72 },
    { jenis_order_name: "PSB OLO", bobot: 6.4, sla_hour: 72 },
    { jenis_order_name: "PSB WIFI", bobot: 5.3, sla_hour: 72 },
    { jenis_order_name: "PDA DATIN", bobot: 6.4, sla_hour: 72 },
    { jenis_order_name: "PDA WIFI", bobot: 5.3, sla_hour: 24 },
    { jenis_order_name: "DISMANTLING EBIS", order_type: "ONT", bobot: 0.67 },
    { jenis_order_name: "DISMANTLING EBIS", order_type: "STB", bobot: 0.67 },
    { jenis_order_name: "DISMANTLING EBIS", order_type: "AP", bobot: 0.67 },
    { jenis_order_name: "DISMANTLING EBIS", order_type: "IP CAMERA", bobot: 0.67 },
    { jenis_order_name: "REPLACEMENT", order_type: "ONT", bobot: 1.33 },
    { jenis_order_name: "REPLACEMENT", order_type: "STB", bobot: 0.67 },
    { jenis_order_name: "Instalasi IP Camera", bobot: 1.6, sla_hour: 72 },
    { jenis_order_name: "Instalasi SD-WAN", bobot: 4, sla_hour: 72 },
    { jenis_order_name: "Instalasi Router", bobot: 2, sla_hour: 72 },
    { jenis_order_name: "Install AP WIFI (1 AP)", bobot: 1.6, sla_hour: 72 },
    { jenis_order_name: "Install AP WIFI (2 AP)", bobot: 1.78, sla_hour: 72 },
    { jenis_order_name: "Install AP WIFI(3 AP)", bobot: 2, sla_hour: 72 },
    { jenis_order_name: "Install AP WIFI (4 AP)", bobot: 2.29, sla_hour: 72 },
    { jenis_order_name: "Pembuatan BAI (Satkomindo,BRI MPLS)", bobot: 0.67 },
  ],
  "PROVISIONING B2C": [
    { jenis_order_name: "2ND STB", bobot: 1.6 },
    { jenis_order_name: "UPSELLING", bobot: 1.1 },
  ],
};
