
import type { GamasPriceItem } from '@/lib/types';

// Data harga dari TA ke Mitra
export const gamasPriceData: GamasPriceItem[] = [
    { "code": "DC-OF-SM-12D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-12D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-12D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 3030 },
    { "code": "DC-OF-SM-24D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-24D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-24D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 3010 },
    { "code": "DC-OF-SM-48D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 48 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-48D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 48 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-48D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 48 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 3060 },
    { "code": "DC-OF-SM-96D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 96 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-96D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 96 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-96D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 96 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 3030 },
    { "code": "DC-OF-SM-144D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 144 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-144D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 144 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-144D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 144 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 3680 },
    { "code": "DC-OF-SM-288D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 288 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-288D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 288 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-288D", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 288 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 3680 },
    { "code": "AC-OF-SM-12D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-AC-OF-SM-12D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-AC-OF-SM-12D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 4220 },
    { "code": "AC-OF-SM-24D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-AC-OF-SM-24D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-AC-OF-SM-24D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 4190 },
    { "code": "AC-OF-SM-48D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 48 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-AC-OF-SM-48D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 48 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-AC-OF-SM-48D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 48 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 4190 },
    { "code": "AC-OF-SM-96D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 96 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-AC-OF-SM-96D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 96 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-AC-OF-SM-96D", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 96 core g 652 d", "unit": "meter", "materialPrice": 0, "servicePrice": 4190 },
    { "code": "DC-OF-SM-12C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-12C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-12C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 3030 },
    { "code": "DC-OF-SM-24C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-24C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-24C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 3030 },
    { "code": "DC-OF-SM-48C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 48 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-48C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 48 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-48C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 48 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 3030 },
    { "code": "DC-OF-SM-96C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 96 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-96C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 96 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-96C", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 96 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 3030 },
    { "code": "AC-OF-SM-12C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-AC-OF-SM-12C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-AC-OF-SM-12C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 4190 },
    { "code": "AC-OF-SM-24C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-AC-OF-SM-24C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-AC-OF-SM-24C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 4190 },
    { "code": "AC-OF-SM-48C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 48 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-AC-OF-SM-48C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 48 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-AC-OF-SM-48C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 48 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 4190 },
    { "code": "AC-OF-SM-96C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 96 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-AC-OF-SM-96C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 96 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-AC-OF-SM-96C", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 96 core g 655 c", "unit": "meter", "materialPrice": 0, "servicePrice": 4190 },
    { "code": "DC-OF-SM-12-SC", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-12-SC", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-12-SC", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 3030 },
    { "code": "DC-OF-SM-24-SC", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-DC-OF-SM-24-SC", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-DC-OF-SM-24-SC", "description": "Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 3030 },
    { "code": "AC-OF-SM-12-SC", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-AC-OF-SM-12-SC", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-AC-OF-SM-12-SC", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 3700 },
    { "code": "AC-OF-SM-24-SC", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-AC-OF-SM-24-SC", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-AC-OF-SM-24-SC", "description": "Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 652 d, \"easy to split\"", "unit": "meter", "materialPrice": 0, "servicePrice": 3700 },
    { "code": "SC-OF-SM-24", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 24 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-SC-OF-SM-24", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 24 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-SC-OF-SM-24", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 24 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 30260 },
    { "code": "SC-OF-SM-48", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 48 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-SC-OF-SM-48", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 48 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-SC-OF-SM-48", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 48 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 30260 },
    { "code": "SC-OF-SM-96", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 96 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-SC-OF-SM-96", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 96 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-SC-OF-SM-96", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 96 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 29800 },
    { "code": "SC-OF-SM-144", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 144 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-SC-OF-SM-144", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 144 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-SC-OF-SM-144", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 144 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 29800 },
    { "code": "SC-OF-SM-288", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 288 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 0 },
    { "code": "M-SC-OF-SM-288", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 288 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-SC-OF-SM-288", "description": "Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 288 core", "unit": "pcs", "materialPrice": 0, "servicePrice": 29800 },
    { "code": "OS-SM-1", "description": "Penyambungan kabel optik single mode kap 1 core dengan cara fusion splice", "unit": "core", "materialPrice": 0, "servicePrice": 0 },
    { "code": "J-OS-SM-1", "description": "Penyambungan kabel optik single mode kap 1 core dengan cara fusion splice", "unit": "core", "materialPrice": 0, "servicePrice": 44810 }
];
