
export type GamasPriceItem = {
    code: string;
    description: string;
    unit: string;
    materialPrice: number;
    servicePrice: number;
};

// Data harga dari TA ke Mitra
export const gamasPriceData: GamasPriceItem[] = [
    { code: 'DC-OF-SM-12D', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 3030 },
    { code: 'DC-OF-SM-24D', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 3010 },
    { code: 'DC-OF-SM-48D', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 48 core g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 3060 },
    { code: 'DC-OF-SM-96D', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 96 core g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 3030 },
    { code: 'DC-OF-SM-144D', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 144 core g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 3680 },
    { code: 'DC-OF-SM-288D', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 288 core g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 3680 },
    { code: 'AC-OF-SM-12D', description: 'Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 4220 },
    { code: 'AC-OF-SM-24D', description: 'Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 4190 },
    { code: 'AC-OF-SM-48D', description: 'Pengadaan dan pemasangan kabel udara fiber optik single mode 48 core g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 4190 },
    { code: 'AC-OF-SM-96D', description: 'Pengadaan dan pemasangan kabel udara fiber optik single mode 96 core g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 4190 },
    { code: 'DC-OF-SM-12C', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 655 c', unit: 'meter', materialPrice: 0, servicePrice: 3030 },
    { code: 'DC-OF-SM-24C', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 655 c', unit: 'meter', materialPrice: 0, servicePrice: 3030 },
    { code: 'DC-OF-SM-48C', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 48 core g 655 c', unit: 'meter', materialPrice: 0, servicePrice: 3030 },
    { code: 'DC-OF-SM-96C', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 96 core g 655 c', unit: 'meter', materialPrice: 0, servicePrice: 3030 },
    { code: 'AC-OF-SM-12C', description: 'Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 655 c', unit: 'meter', materialPrice: 0, servicePrice: 4190 },
    { code: 'AC-OF-SM-24C', description: 'Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 655 c', unit: 'meter', materialPrice: 0, servicePrice: 4190 },
    { code: 'AC-OF-SM-48C', description: 'Pengadaan dan pemasangan kabel udara fiber optik single mode 48 core g 655 c', unit: 'meter', materialPrice: 0, servicePrice: 4190 },
    { code: 'AC-OF-SM-96C', description: 'Pengadaan dan pemasangan kabel udara fiber optik single mode 96 core g 655 c', unit: 'meter', materialPrice: 0, servicePrice: 4190 },
    { code: 'DC-OF-SM-12-SC', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 12 core g 652 d, "easy to split"', unit: 'meter', materialPrice: 0, servicePrice: 3030 },
    { code: 'DC-OF-SM-24-SC', description: 'Pengadaan dan pemasangan kabel duct fiber optik single mode 24 core g 652 d, "easy to split"', unit: 'meter', materialPrice: 0, servicePrice: 3030 },
    { code: 'AC-OF-SM-12-SC', description: 'Pengadaan dan pemasangan kabel udara fiber optik single mode 12 core g 652 d, "easy to split"', unit: 'meter', materialPrice: 0, servicePrice: 3700 },
    { code: 'AC-OF-SM-24-SC', description: 'Pengadaan dan pemasangan kabel udara fiber optik single mode 24 core g 652 d, "easy to split"', unit: 'meter', materialPrice: 0, servicePrice: 3700 },
    { code: 'SC-OF-SM-24', description: 'Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 24 core', unit: 'pcs', materialPrice: 0, servicePrice: 30260 },
    { code: 'SC-OF-SM-48', description: 'Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 48 core', unit: 'pcs', materialPrice: 0, servicePrice: 30260 },
    { code: 'SC-OF-SM-96', description: 'Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 96 core', unit: 'pcs', materialPrice: 0, servicePrice: 29800 },
    { code: 'SC-OF-SM-144', description: 'Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 144 core', unit: 'pcs', materialPrice: 0, servicePrice: 29800 },
    { code: 'SC-OF-SM-288', description: 'Pengadaan dan pemasangan alat sambung (cabang/ lurus) untuk fiber optik kapasitas 12 - 288 core', unit: 'pcs', materialPrice: 0, servicePrice: 29800 },
    { code: 'OS-SM-1', description: 'Penyambungan kabel optik single mode kap 1 core dengan cara fusion splice', unit: 'core', materialPrice: 0, servicePrice: 44810 },
    { code: 'AB-OF-SM-2D', description: 'Pengadaan dan pemasangan air blown cable optik, single mode 2 core, g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 2100 },
    { code: 'AB-OF-SM-4D', description: 'Pengadaan dan pemasangan air blown cable optik, single mode 4 core, g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 2100 },
    { code: 'AB-OF-SM-8D', description: 'Pengadaan dan pemasangan air blown cable optik, single mode core, g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 2100 },
    { code: 'AB-OF-SM-12D', description: 'Pengadaan dan pemasangan air blown cable optik, single mode 12 core, g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 2100 },
    { code: 'AB-OF-SM-24D', description: 'Pengadaan dan pemasangan air blown cable optik, single mode 24 core, g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 2980 },
    { code: 'AB-OF-SM-48D', description: 'Pengadaan dan pemasangan air blown cable optik, single mode 48 core, g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 2980 },
    { code: 'AB-OF-SM-72D', description: 'Pengadaan dan pemasangan air blown cable optik, single mode 72 core, g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 2980 },
    { code: 'AB-OF-SM-96D', description: 'Pengadaan dan pemasangan air blown cable optik, single mode 96 core, g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 2940 },
    { code: 'AB-OF-SM-144D', description: 'Pengadaan dan pemasangan air blown cable optik, single mode 144 core, g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 3360 },
    { code: 'AB-OF-SM-288D', description: 'Pengadaan dan pemasangan air blown cable optik, single mode 288 core, g 652 d', unit: 'meter', materialPrice: 0, servicePrice: 4200 },
    { code: 'PC-APC-657-2', description: 'Pengadaan dan pemasangan patch cord 2 meter, (fc/lc/sc-apc to fc/lc/sc-apc), g.657', unit: 'pcs', materialPrice: 0, servicePrice: 2560 },
    { code: 'PC-APC/UPC-657-A1', description: 'Additional patch cord, g.657', unit: 'meter', materialPrice: 0, servicePrice: 1280 },
    { code: 'PC-UPC-657-2', description: 'Pengadaan dan pemasangan patch cord 2 meter, (fc/lc/sc-upc to fc/lc/sc-upc), g.657', unit: 'pcs', materialPrice: 0, servicePrice: 2640 },
    { code: 'PC-APC-655-2', description: 'Pengadaan dan pemasangan patch cord 2 meter, (fc/lc/sc-apc to fc/lc/sc-apc), g.655c', unit: 'pcs', materialPrice: 0, servicePrice: 2640 },
    { code: 'PC-APC/UPC-655-A1', description: 'Additional patch cord, g.655', unit: 'meter', materialPrice: 0, servicePrice: 1310 },
    { code: 'PC-UPC-655-2', description: 'Pengadaan dan pemasangan patch cord 2 meter, (fc/lc/sc-upc to fc/lc/sc-upc), g.655c', unit: 'pcs', materialPrice: 0, servicePrice: 2640 },
    { code: 'PC-APC-652-2', description: 'Pengadaan dan pemasangan patch cord 2 meter, (fc/lc/sc-apc to fc/lc/sc-apc), g.652 d', unit: 'pcs', materialPrice: 0, servicePrice: 2640 },
    { code: 'PC-APC/UPC-652-A1', description: 'Additional patch cord, g.652d', unit: 'meter', materialPrice: 0, servicePrice: 1330 },
    { code: 'PC-UPC-652-2', description: 'Pengadaan dan pemasangan patch cord 2 meter, (fc/lc/sc-upc to fc/lc/sc-upc), g.652d', unit: 'pcs', materialPrice: 0, servicePrice: 2680 },
    { code: 'ODC-C-48', description: 'Pengadaan dan pemasangan odc-pole (outdoor) dengan space untuk spliter modular termasuk material adaptor sc kap 48 core, berikut pelabelan', unit: 'pcs', materialPrice: 0, servicePrice: 3642000 },
    { code: 'ODC-C-96', description: 'Pengadaan dan pemasangan kabinet odc (outdoor) kap 96 core dengan space untuk spliter modular termasuk material adaptor sc, pigtail, pondasi berlapis keramik, lantai kerja keramik, patok pengaman (5 buah), berikut pelabelan', unit: 'pcs', materialPrice: 0, servicePrice: 4558000 },
    { code: 'ODC-C-144', description: 'Pengadaan dan pemasangan kabinet odc (outdoor) kap 144 core dengan space untuk spliter modular termasuk material adaptor sc, pigtail, pondasi berlapis keramik, lantai kerja keramik, patok pengaman (5 buah), berikut pelabelan', unit: 'pcs', materialPrice: 0, servicePrice: 4921000 },
    { code: 'ODC-C-288', description: 'Pengadaan dan pemasangan kabinet odc (outdoor) kap 288 core dengan space untuk spliter modular termasuk material adaptor sc, pigtail, pondasi berlapis keramik, lantai kerja keramik, patok pengaman (5 buah), berikut pelabelan', unit: 'pcs', materialPrice: 0, servicePrice: 4958000 },
    { code: 'ODC-C-576', description: 'Pengadaan dan pemasangan kabinet odc (outdoor) kap 576 core dengan space untuk spliter modular termasuk material adaptor sc, pigtail, pondasi berlapis keramik, lantai kerja keramik, patok pengaman (5 buah), berikut pelabelan', unit: 'pcs', materialPrice: 0, servicePrice: 4920000 },
    { code: 'ODC-C-144-PKU', description: 'Pengadaan dan pemasangan kabinet odc (outdoor) kap 144 core dengan space untuk spliter modular termasuk material adaptor sc, pigtail, ditempatkan pada 2 tiang besi 7m yang dilengkapi besi penyangga antar tiang dengan rangka besi odc dan bordes lantai kerja serta grounding 5m luas penampang minimal 25mm untuk penempatan kabel fo dan grounding 1 titik menggunakan anchoring, span wartel dan slack support 2 buah', unit: 'set', materialPrice: 0, servicePrice: 7529000 },
    { code: 'ODC-C-288-PKU', description: 'Pengadaan dan pemasangan kabinet odc (outdoor) kap 288 core dengan space untuk spliter modular termasuk material adaptor sc, pigtail, ditempatkan pada 2 tiang besi 7m yang dilengkapi besi penyangga antar tiang dengan rangka besi odc dan bordes lantai kerja serta grounding 5m luas penampang minimal 25mm untuk penempatan kabel fo dan grounding 1 titik, menggunakan anchoring, span wartel dan slack support 2 buah', unit: 'set', materialPrice: 0, servicePrice: 7566000 },
    { code: 'ODC-C-144-PKT', description: 'Pengadaan dan pemasangan kabinet odc (outdoor) kap 144 core dengan space untuk spliter modular termasuk material adaptor sc, pigtail, ditempatkan pada 2 tiang besi 7m yang dilengkapi besi penyangga antar tiang dengan rangka besi odc dan bordes lantai kerja serta grounding 5m luas penampang minimal 25mm untuk penempatan kabel fo dan grounding 1 titik, menggunakan 1 buah riser pipe 2” panjang 3m termasuk handhole odc portable', unit: 'set', materialPrice: 0, servicePrice: 7991000 },
    { code: 'ODC-C-288-PKT', description: 'Pengadaan dan pemasangan kabinet odc (outdoor) kap 288 core dengan space untuk spliter modular termasuk material adaptor sc, pigtail, ditempatkan pada 2 tiang besi 7m yang dilengkapi besi penyangga antar tiang dengan rangka besi odc dan bordes lantai kerja serta grounding 5m luas penampang minimal 25mm untuk penempatan kabel fo dan grounding 1 titik, menggunakan 1 buah riser pipe 2” panjang 3m termasuk handhole odc portable', unit: 'set', materialPrice: 0, servicePrice: 8028000 },
    { code: 'ODC-PROT-144', description: 'Pengaman odc 144 (besi siku 4cmx4cmx4mm, besi beton 10mm (jarak antar besi beton 10cm, engsel besar, baut ram set 14mm dan kunci gembok 50mm', unit: 'unit', materialPrice: 1482000, servicePrice: 679000 },
    { code: 'ODC-PROT-288', description: 'Pengaman odc 288 (besi siku 4cmx4cmx4mm, besi beton 10mm (jarak antar besi beton 10cm, engsel besar, baut ram set 14mm dan kunci gembok 50mm', unit: 'unit', materialPrice: 1609000, servicePrice: 727500 },
    { code: 'Base Tray ODC', description: 'Pengadaan dan pemasangan otb termasuk terminasi dan penyambungan kabel optik single mode kap 12 core serta adapter (sc connector), pigtail dan protection sleeve pada cassette/box', unit: 'pcs', materialPrice: 0, servicePrice: 641900 },
    { code: 'ODP-SOLID-PL-8', description: 'Pengadaan dan pemasangan odp ( pilar ) solid kap 8 core termasuk pigtail, berikut space 1 splitter (1:8), printing dan pelabelan penempelan qr code (qr code disediakan oleh telkom)', unit: 'pcs', materialPrice: 0, servicePrice: 119200 },
    { code: 'ODP-SOLID-PL-16', description: 'Pengadaan dan pemasangan odp ( pilar ) solid kap 16 core termasuk pigtail, berikut space 1 splitter (1:16), printing dan pelabelan penempelan qr code (qr code disediakan oleh telkom)', unit: 'pcs', materialPrice: 0, servicePrice: 119200 },
    { code: 'TC-SM-12', description: 'Pengadaan dan pemasangan otb termasuk terminasi dan penyambungan kabel optik single mode kap 12 core serta adapter (sc connector), pigtail dan protection sleeve pada cassette/box', unit: 'pcs', materialPrice: 0, servicePrice: 271600 },
    { code: 'TC-SM-24', description: 'Pengadaan dan pemasangan otb termasuk terminasi dan penyambungan kabel optik single mode kap 24 core serta adapter (sc connector), pigtail dan protection sleeve pada cassette/box', unit: 'pcs', materialPrice: 0, servicePrice: 630500 },
    { code: 'TC-SM-48', description: 'Pengadaan dan pemasangan otb termasuk terminasi dan penyambungan kabel optik single mode kap 48 core serta adapter (sc connector), pigtail dan protection sleeve pada cassette/box', unit: 'pcs', materialPrice: 0, servicePrice: 1794000 },
    { code: 'TC-SM-96', description: 'Pengadaan dan pemasangan otb termasuk terminasi dan penyambungan kabel optik single mode kap 96 core serta adapter (sc connector), pigtail dan protection sleeve pada cassette/box', unit: 'pcs', materialPrice: 0, servicePrice: 5178000 },
    { code: 'PS-1-2-ODC', description: 'Pengadaan dan pemasangan passive splitter 1:2, type modular sc/upc, for odc, termasuk pigtail', unit: 'pcs', materialPrice: 0, servicePrice: 29650 },
    { code: 'PS-1-4-ODC', description: 'Pengadaan dan pemasangan passive splitter 1:4, type modular sc/upc, for odc, termasuk pigtail', unit: 'pcs', materialPrice: 0, servicePrice: 30110 },
    { code: 'PS-1-8-ODX', description: 'Pengadaan dan pemasangan passive splitter 1:8, type modular sc/upc, for odp, termasuk pigtail', unit: 'pcs', materialPrice: 0, servicePrice: 29650 },
    { code: 'PS-1-8-ODX-S', description: 'Pengadaan dan pemasangan passive splitter solid 1:8, type solid sc/upc, for odp, termasuk pigtail', unit: 'pcs', materialPrice: 0, servicePrice: 29650 },
    { code: 'PS-1-16-ODP', description: 'Pengadaan dan pemasangan passive splitter 1:16, type modular sc/upc, for odp, termasuk pigtail', unit: 'pcs', materialPrice: 0, servicePrice: 29650 },
    { code: 'PS-1-16-ODP-S', description: 'Pengadaan dan pemasangan passive splitter solid 1:16, type solid sc/upc, for odp, termasuk pigtail', unit: 'pcs', materialPrice: 0, servicePrice: 29650 },
    { code: 'PS-2-2-ODC', description: 'Pengadaan dan pemasangan passive splitter 2:2, type modular sc/upc, for odc, termasuk pigtail', unit: 'pcs', materialPrice: 0, servicePrice: 29870 },
    { code: 'PS-2-4-ODC', description: 'Pengadaan dan pemasangan passive splitter 2:4, type modular sc/upc, for odc, termasuk pigtail', unit: 'pcs', materialPrice: 0, servicePrice: 29870 },
    { code: 'PS-2-8-ODX', description: 'Pengadaan dan pemasangan passive splitter 2:8, type modular sc/upc, for odc, termasuk pigtail', unit: 'pcs', materialPrice: 0, servicePrice: 33950 },
    { code: 'PS-1-32-ODX', description: 'Pengadaan dan pemasangan passive splitter 1:32, type modular sc/upc, for odc/odp, termasuk pigtail', unit: 'pcs', materialPrice: 0, servicePrice: 33950 },
    { code: 'SITAC ODC', description: 'Akuisisi lahan sitac odc', unit: 'Node', materialPrice: 0, servicePrice: 6473000 },
    { code: 'PU-S7.0-140', description: 'Pengadaan dan pemasangan tiang besi 7 meter, berikut cat & cor pondasi dan assesories dengan kekuatan tarik 140 kg', unit: 'Unit', materialPrice: 0, servicePrice: 213400 },
    { code: 'PU-S9.0-140', description: 'Pengadaan dan pemasangan tiang besi 9 meter, berikut cat & cor dan assesories dengan kekuatan tarik 140 kg', unit: 'Unit', materialPrice: 0, servicePrice: 213900 },
    { code: 'GU-G', description: 'Pengadaan dan pemasangan temberang tarik', unit: 'pcs', materialPrice: 0, servicePrice: 52950 },
    { code: 'GB-G1', description: 'Pengadaan dan pemasangan grounding 1 titik rod pada odp /kotak pembagi dengan tahanan maks 3 ohm', unit: 'pcs', materialPrice: 658800, servicePrice: 355900 },
    { code: 'GB-G3', description: 'Pengadaan dan pemasangan grounding 3 titik rod pada odc dengan tahanan maks 1 ohm', unit: 'pcs', materialPrice: 1984000, servicePrice: 412600 },
    { code: 'GB-G-INTG', description: 'Pengadaan dan pemasangan material grounding di lokasi gedung eksisting dengan cara integrasi', unit: 'pcs', materialPrice: 199200, servicePrice: 143400 },
    { code: 'TC-02-ODC', description: 'Pengadaan dan pemasangan riser pipe untuk pengaman kabel optik ke odc pole / titik naik ku diamater 2 inch panjang 3 meter', unit: 'pcs', materialPrice: 0, servicePrice: 54010 },
    { code: 'PP-OF-IN', description: 'Pengadaan dan pemasangan pipe protector indoor cable (pvc white) high impact conduit 20 mm', unit: 'meter', materialPrice: 19680, servicePrice: 3520 },
    { code: 'DD-S3-1', description: 'Pengadaan dan pemasangan pipa besi diameter 100 mm dan ketebalan pipa 3,65 mm untuk crossing 1 pipa bentang ≤ 6 meter', unit: 'meter', materialPrice: 0, servicePrice: 52870 },
    { code: 'DD-S3-2', description: 'Pengadaan dan pemasangan pipa besi diameter 100 mm dan ketebalan pipa 3,65 mm untuk crossing 2 pipa bentang ≤ 6 meter', unit: 'meter', materialPrice: 0, servicePrice: 70500 },
    { code: 'DD-S3-3', description: 'Pengadaan dan pemasangan pipa besi diameter 100 mm dan ketebalan pipa 3,65 mm untuk crossing 3 pipa bentang ≤ 6 meter', unit: 'meter', materialPrice: 0, servicePrice: 105700 },
    { code: 'DD-V4-1', description: 'Pengadan dan pemasangan pipa duct pvc diameter dalam 100 mm, ketebalan 4 mm, 1 pipa termasuk pengecoran', unit: 'meter', materialPrice: 0, servicePrice: 52870 },
    { code: 'DD-V4-2', description: 'Pengadan dan pemasangan pipa duct pvc diameter dalam 100 mm, ketebalan 4 mm, 2 pipa termasuk pengecoran', unit: 'meter', materialPrice: 0, servicePrice: 70610 },
    { code: 'DD-V5-1', description: 'Pemasangan pipa duct dengan selubung pasir dia 100 mm dengan ketebalan 5,5 mm, 1 pipa ( crossing )', unit: 'meter', materialPrice: 0, servicePrice: 52870 },
    { code: 'DD-V5-2', description: 'Pemasangan pipa duct dengan selubung pasir dia 100 mm dengan ketebalan 5,5 mm, 2 pipa ( crossing )', unit: 'meter', materialPrice: 0, servicePrice: 70500 },
    { code: 'DD-DA-S1', description: 'Pengadaan dan pemasangan pipa duct menempel pada jembatan existing menggunakan pipa galvanis diamenter 100 mm, tebal 3,65 mm, 1 pipa', unit: 'meter', materialPrice: 0, servicePrice: 214700 },
    { code: 'DD-DA-S2', description: 'Pengadaan dan pemasangan pipa duct menempel pada jembatan existing menggunakan pipa galvanis diamenter 100 mm, tebal 3,65 mm, 2 pipa', unit: 'meter', materialPrice: 0, servicePrice: 423000 },
    { code: 'DD-DA-S4', description: 'Pengadaan dan pemasangan pipa duct menempel pada jembatan existing menggunakan pipa galvanis diamenter 100 mm, tebal 3,65 mm, 4 pipa', unit: 'meter', materialPrice: 0, servicePrice: 846000 },
    { code: 'DD-BSS-S1', description: 'Pengadaan dan pemasangan pipa duct pada jembatan dengan self support berpenguatan menggunakan pipa besi galv 1 pipa, bentang 6 - 12 meter', unit: 'meter', materialPrice: 0, servicePrice: 211500 },
    { code: 'DD-BSS-S2', description: 'Pengadaan dan pemasangan pipa duct pada jembatan dengan self support berpenguatan menggunakan pipa besi galv 2 pipa, bentang 6 - 12 meter', unit: 'meter', materialPrice: 0, servicePrice: 423000 },
    { code: 'DD-BTS-S1', description: 'Pengadaan dan pemasangan pipa duct pada jembatan menggunakan pipa besi galv 1 pipa, bentang 6 - 12 meter', unit: 'meter', materialPrice: 0, servicePrice: 211500 },
    { code: 'DD-BTS-S2', description: 'Pengadaan dan pemasangan pipa duct pada jembatan menggunakan pipa besi galv 2 pipa, bentang 6 - 12 meter', unit: 'meter', materialPrice: 0, servicePrice: 423000 },
    { code: 'DD-BTS-S4', description: 'Pengadaan dan pemasangan pipa duct pada jembatan menggunakan pipa besi galv 4 pipa, bentang 6 - 12 meter', unit: 'meter', materialPrice: 0, servicePrice: 641200 },
    { code: 'HB-PS-1', description: 'Pengadaan dan pemasangan pipa duct dengan system gantung 1 tiang besi, bentang s/d 40 meter', unit: 'meter', materialPrice: 0, servicePrice: 34230 },
    { code: 'HB-PS-2', description: 'Pengadaan dan pemasangan pipa duct dengan system gantung 2 tiang besi, bentang s/d 100 meter', unit: 'meter', materialPrice: 0, servicePrice: 40460 },
    { code: 'HB-PS-4', description: 'Pengadaan dan pemasangan pipa duct dengan system gantung 4 tiang besi, bentang ≥ 100 meter', unit: 'meter', materialPrice: 0, servicePrice: 47200 },
    { code: 'DD-BMR-1', description: 'Pengadaan dan pemasangan boring pada lintasan kereta api menggunakan 1 pipa galvanis diameter 100 mm tebal 3,65 mm', unit: 'track', materialPrice: 0, servicePrice: 19420000 },
    { code: 'DD-BMR-2', description: 'Pengadaan dan pemasangan boring pada lintasan kereta api menggunakan 2 pipa galvanis diameter 100 mm tebal 3,65 mm', unit: 'track', materialPrice: 0, servicePrice: 29130000 },
    { code: 'DD-BMR-4', description: 'Pengadaan dan pemasangan boring pada lintasan kereta api menggunakan 4 pipa galvanis diameter 100 mm tebal 3,65 mm', unit: 'track', materialPrice: 0, servicePrice: 38840000 },
    { code: 'DC-SD-28-1', description: 'Pengadaan dan pemasangan 1 subduct 28/32 mm pada polongan route duct', unit: 'meter', materialPrice: 0, servicePrice: 1450 },
    { code: 'DC-SD-28-3', description: 'Pengadaan dan pemasangan 1 subduct 28/32 mm pada polongan route duct, 3 pipa', unit: 'meter', materialPrice: 0, servicePrice: 1870 },
    { code: 'DC-SD-33-1', description: 'Pengadaan dan pemasangan 1 subduct 40/33 pada polongan route duct', unit: 'meter', materialPrice: 0, servicePrice: 1450 },
    { code: 'DC-SD-33-2', description: 'Pengadaan dan pemasangan 1 subduct 40/33 pada polongan route duct, 2 pipa', unit: 'meter', materialPrice: 0, servicePrice: 1860 },
    { code: 'DC-SD-43-1', description: 'Pengadaan dan pemasangan 1 subduct 50/42 pada polongan route duct', unit: 'meter', materialPrice: 0, servicePrice: 1430 },
    { code: 'DC-SD-43-2', description: 'Engadaan dan pemasangan 1 subduct 50/42 pada polongan route duct, 2 pipa', unit: 'meter', materialPrice: 0, servicePrice: 1860 },
    { code: 'DCD-PVC-1', description: 'Pengadaan dan pemasangan duct cable penanggal diameter pipa pvc 2 inch (class aw) 1 pipa', unit: 'meter', materialPrice: 0, servicePrice: 1410 },
    { code: 'DD-BM-100-1', description: 'Pengadaan dan pemasangan pipa galvanis dengan ukuran diameter 100 mm dan ketebalan 3,65 mm dengan cara boring manual /mesin 1 pipa dengan kedalaman minimal 150 cm', unit: 'meter', materialPrice: 0, servicePrice: 62530 },
    { code: 'DD-BM-100-2', description: 'Pengadaan dan pemasangan pipa galvanis dengan ukuran diameter 100 mm dan ketebalan 3,65 mm dengan cara boring manual /mesin 1 pipa dengan kedalaman minimal 150 cm, 2 pipa', unit: 'meter', materialPrice: 0, servicePrice: 64860 },
    { code: 'DD-BM-50-1', description: 'Pengadaan dan pemasangan pipa galvanis dengan ukuran diameter 50 mm dan ketebalan 2,7 mm cara boring manual /mesin 1 pipa dengan kedalaman minimal 150 cm', unit: 'meter', materialPrice: 0, servicePrice: 32190 },
    { code: 'DD-BM-50-2', description: 'Pengadaan dan pemasangan pipa galvanis dengan ukuran diameter 50 mm dan ketebalan 2,7 mm cara boring manual /mesin 2 pipa dengan kedalaman minimal 150 cm', unit: 'meter', materialPrice: 0, servicePrice: 32190 },
    { code: 'DD-BM-HDPE-40-1', description: 'Pekerjaan boring manual (rojok) hdpe 40/33 mm 1 pipa dengan kedalaman 1,5 meter', unit: 'meter', materialPrice: 0, servicePrice: 30550 },
    { code: 'DD-BM-HDPE-50-1', description: 'Pekerjaan boring manual (rojok) hdpe 50/42 mm 1 pipa dengan kedalaman 1,5 meter', unit: 'meter', materialPrice: 0, servicePrice: 32130 },
    { code: 'DD-HDPE-40-1', description: 'Pengadaan dan pemasangan pipa hdpe 40/33 mm 1 pipa dengan kedalaman 1,5 meter', unit: 'meter', materialPrice: 0, servicePrice: 1290 },
    { code: 'DD-HDPE-40-2', description: 'Pengadaan dan pemasangan pipa hdpe 40/33 mm 2 pipa dengan kedalaman 1,5 meter', unit: 'meter', materialPrice: 0, servicePrice: 1650 },
    { code: 'DD-HDPE-50-1', description: 'Pengadaan dan pemasangan pipa hdpe 50/42 mm 1 pipa dengan kedalaman 1,5 meter', unit: 'meter', materialPrice: 0, servicePrice: 1360 },
    { code: 'DD-HDPE-50-2', description: 'Pengadaan dan pemasangan pipa hdpe 50/42 mm 2 pipa dengan kedalaman 1,5 meter', unit: 'meter', materialPrice: 0, servicePrice: 1650 },
    { code: 'DD-HDPE-40-1C', description: 'Pengadaan dan pemasangan pipa hdpe 40/33 mm 1 pipa dengan kedalaman 1,5 meter sudah termasuk connector hdpe tipe compression fitting', unit: 'meter', materialPrice: 0, servicePrice: 1360 },
    { code: 'DD-HDPE-40-2C', description: 'Pengadaan dan pemasangan pipa hdpe 40/33 mm 2 pipa dengan kedalaman 1,5 meter sudah termasuk connector hdpe tipe compression fitting', unit: 'meter', materialPrice: 0, servicePrice: 1650 },
    { code: 'DD-ROD', description: 'Pekerjaan pembersihan pada route duct yang kosong / rodding duct existing.', unit: 'meter', materialPrice: 0, servicePrice: 1760 },
    { code: 'DD-RV-1', description: 'Pekerjaan perbaikan route duct / hdpe, 1 pipa.', unit: 'meter', materialPrice: 28970, servicePrice: 70500 },
    { code: 'DD-RV-CONCRETE', description: 'Pekerjaan bobok dinding mh / hh termasuk perbaikan kembali', unit: 'm3', materialPrice: 849200, servicePrice: 634500 },
    { code: 'DD-DS-S1', description: 'Pengadaan dan pemasangan duct baru dengan cara melakukan boring dibawah dasar parit/sungai dengan kedalaman 1,5 m dengan menggunakan pvc diamater 100 mm dan ketebalan 5,5 mm 1 pipa', unit: 'meter', materialPrice: 0, servicePrice: 148000 },
    { code: 'DD-DS-COD1-M', description: 'Pengadaan dan pemasangan duct baru type cod, dengan mesin pengeboran (borring) dibawah parit, pada kedalaman 1,50 m di bawah dasar selokan, tanpa perlindungan pvc, 1 pipa', unit: 'meter', materialPrice: 0, servicePrice: 415100 },
    { code: 'Klem HDPE', description: 'Pengkleman hdpe di dinding beton dengan klem ketebalan 2mm lebar 2,5 cm menggunakan dynabolt termasuk rekondisi atau perbaikan kerusakan', unit: 'pcs', materialPrice: 0, servicePrice: 2230 },
    { code: 'BC-TR-0.4', description: 'Pekerjaan galian, pengurugan kembali dan perbaikan kembali, pengisian pasir, warning tape dan tanda rute kabel serta tempat sambung kedalaman 0.4 meter', unit: 'meter', materialPrice: 0, servicePrice: 11680 },
    { code: 'BC-TR-0.6', description: 'Pekerjaan galian, pengurugan kembali dan perbaikan kembali, pengisian pasir, warning tape dan tanda rute kabel serta tempat sambung, kedalaman 0,6 meter', unit: 'meter', materialPrice: 0, servicePrice: 15160 },
    { code: 'BC-TR-1', description: 'Pekerjaan galian, pengurugan kembali dan perbaikan kembali, pengisian pasir, warning tape dan tanda rute kabel serta tempat sambung, kedalaman 1 meter', unit: 'meter', materialPrice: 0, servicePrice: 22950 },
    { code: 'BC-TR-2', description: 'Pekerjaan galian, pengurugan kembali dan perbaikan kembali, pengisian pasir, warning tape dan tanda rute kabel serta tempat sambung, kedalaman 1,2 meter', unit: 'meter', materialPrice: 0, servicePrice: 27050 },
    { code: 'BC-TR-3', description: 'Pekerjaan galian, pengurugan kembali dan perbaikan kembali, pengisian pasir, warning tape dan tanda rute kabel serta tempat sambung, kedalaman 1,3 meter', unit: 'meter', materialPrice: 0, servicePrice: 28800 },
    { code: 'BC-TR-4', description: 'Pekerjaan galian, pengurugan kembali dan perbaikan kembali, pengisian pasir, warning tape dan tanda rute kabel serta tempat sambung, kedalaman 1,4 meter', unit: 'meter', materialPrice: 0, servicePrice: 30870 },
    { code: 'BC-TR-5', description: 'Pekerjaan galian, pengurugan kembali dan perbaikan kembali, pengisian pasir, warning tape dan tanda rute kabel serta tempat sambung kedalaman 1,5 meter', unit: 'meter', materialPrice: 0, servicePrice: 32810 },
    { code: 'BCTR-ROCK', description: 'Pengadaan galian batu masif kedalaman 1,5 meter, panjang minimum 5 m, termasuk pengadaan marking post', unit: 'meter', materialPrice: 0, servicePrice: 189700 },
    { code: 'BC-MTR-0.4', description: 'Pekerjaan galian pada permukaan jalan aspal dengan lebar galian 8 cm dan kedalaman 40 cm, termasuk pemetaan utility eksisting dengan metode geo penetrating radar, perbaikan, pengurugan (backfilling) menggunakan concrete type k225 dan pengaspalan', unit: 'meter', materialPrice: 0, servicePrice: 179000 },
    { code: 'BD-SK', description: 'Pekerjaan bobokan dan perbaikan Dinding Chamber / BTS / STO untuk lubang Sparing Kabel', unit: 'Titik', materialPrice: 41080, servicePrice: 71590 },
    { code: 'SMD-ABS-2A', description: 'Pengadaan dan pemasangan Alat Sambung Micro Duct cabang / lurus 2 cabang,termasuk gas block (seal).', unit: 'pcs', materialPrice: 0, servicePrice: 138000 },
    { code: 'SMD-ABS-3A', description: 'Pengadaan dan pemasangan Alat Sambung Micro Duct cabang / lurus 3 cabang,termasuk gas block (seal).', unit: 'pcs', materialPrice: 0, servicePrice: 149100 },
    { code: 'SMD-ABS-4A', description: 'Pengadaan dan pemasangan Alat Sambung Micro Duct cabang / lurus 4 cabang,termasuk gas block (seal).', unit: 'pcs', materialPrice: 0, servicePrice: 164000 },
    { code: 'SMD-ABS-6A', description: 'Pengadaan dan pemasangan Alat Sambung Micro Duct cabang / lurus 6 cabang,termasuk gas block (seal).', unit: 'pcs', materialPrice: 0, servicePrice: 180400 },
    { code: 'DD-MDSC-5/3.5', description: 'Pengadaan dan Pemasangan Straight Connector 5/3,5 mm', unit: 'pcs', materialPrice: 0, servicePrice: 450 },
    { code: 'DD-MDSC-10/8', description: 'Pengadaan dan Pemasangan Straight Connector 10/8 mm', unit: 'pcs', materialPrice: 0, servicePrice: 450 },
    { code: 'DD-MDSC-12/10', description: 'Pengadaan dan Pemasangan Straight Connector 12/10 mm', unit: 'pcs', materialPrice: 0, servicePrice: 450 },
    { code: 'DD-MDDI-1A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Install, 1 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 1620 },
    { code: 'DD-MDDI-2A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Install, 2 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 2130 },
    { code: 'DD-MDDI-4A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Install, 4 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 2440 },
    { code: 'DD-MDDI-7A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Install, 7 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 2460 },
    { code: 'DD-MDDI-12A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Install, 12 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 2830 },
    { code: 'DD-MDDI-19A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Install, 19 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3300 },
    { code: 'DD-MDDI-24A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Install, 24 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3760 },
    { code: 'DD-MDDI-1B', description: 'Pengadaan dan Pemasangan Micro Duct 10/8mm, Direct Install, 1 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 2090 },
    { code: 'DD-MDDI-2B', description: 'Pengadaan dan Pemasangan Micro Duct 10/8mm, Direct Install, 2 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 2440 },
    { code: 'DD-MDDI-4B', description: 'Pengadaan dan Pemasangan Micro Duct 10/8mm, Direct Install, 4 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 2790 },
    { code: 'DD-MDDI-7B', description: 'Pengadaan dan Pemasangan Micro Duct 10/8mm, Direct Install, 7 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3220 },
    { code: 'DD-MDDI-1C', description: 'Pengadaan dan Pemasangan Micro Duct 12/10mm, Direct Install, 1 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 2640 },
    { code: 'DD-MDDI-2C', description: 'Pengadaan dan Pemasangan Micro Duct 12/10mm, Direct Install, 2 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3030 },
    { code: 'DD-MDDI-4C', description: 'Pengadaan dan Pemasangan Micro Duct 12/10mm, Direct Install, 4 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3760 },
    { code: 'DD-MDDI-7C', description: 'Pengadaan dan Pemasangan Micro Duct 12/10mm, Direct Install, 7 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 4030 },
    { code: 'DD-MDDI-1D', description: 'Pengadaan dan Pemasangan Micro Duct 16/14mm, Direct Install, 1 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 2790 },
    { code: 'DD-MDDI-2D', description: 'Pengadaan dan Pemasangan Micro Duct 16/14mm, Direct Install, 2 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3200 },
    { code: 'DD-MDDB-1A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Buried, 1 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 2380 },
    { code: 'DD-MDDB-2A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Buried, 2 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3130 },
    { code: 'DD-MDDB-4A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Buried, 4 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3580 },
    { code: 'DD-MDDB-7A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Buried,7 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3610 },
    { code: 'DD-MDDB-12A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Buried, 12 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 4150 },
    { code: 'DD-MDDB-19A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Buried, 19 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 4840 },
    { code: 'DD-MDDB-24A', description: 'Pengadaan dan Pemasangan Micro Duct 5/3.5mm, Direct Buried, 24 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 5520 },
    { code: 'DD-MDDB-1B', description: 'Pengadaan dan Pemasangan Micro Duct 10/8mm, Direct Buried, 1 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3070 },
    { code: 'DD-MDDB-2B', description: 'Pengadaan dan Pemasangan Micro Duct 10/8mm, Direct Buried, 2 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3580 },
    { code: 'DD-MDDB-4B', description: 'Pengadaan dan Pemasangan Micro Duct 10/8mm, Direct Buried, 4 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 4100 },
    { code: 'DD-MDDB-7B', description: 'Pengadaan dan Pemasangan Micro Duct 10/8mm, Direct Buried, 7 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 4720 },
    { code: 'DD-MDDB-1C', description: 'Pengadaan dan Pemasangan Micro Duct 12/10mm, Direct Buried, 1 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 3870 },
    { code: 'DD-MDDB-2C', description: 'Pengadaan dan Pemasangan Micro Duct 12/10mm, Direct Buried, 2 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 4440 },
    { code: 'DD-MDDB-4C', description: 'Pengadaan dan Pemasangan Micro Duct 12/10mm, Direct Buried, 4 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 5480 },
    { code: 'DD-MDDB-7C', description: 'Pengadaan dan Pemasangan Micro Duct 12/10mm, Direct Buried, 7 way, untuk Air / Water Blowing kabel FO termasuk connector', unit: 'meter', materialPrice: 0, servicePrice: 5920 },
    { code: 'DD-MDEC-5/3.5', description: 'Pengadaan dan Pemasangan End Cap 5/3,5 mm', unit: 'pcs', materialPrice: 0, servicePrice: 450 },
    { code: 'DD-MDEC-10/8', description: 'Pengadaan dan Pemasangan End Cap 10/8 mm', unit: 'pcs', materialPrice: 0, servicePrice: 450 },
    { code: 'DD-MDEC-12/10', description: 'Pengadaan dan Pemasangan End Cap 12/10 mm', unit: 'pcs', materialPrice: 0, servicePrice: 450 },
    { code: 'FID-28-1', description: 'Fabric Innerduct diameter 28mm 1 polongan', unit: 'meter', materialPrice: 0, servicePrice: 1760 },
    { code: 'FID-28-2', description: 'Fabric Innerduct diameter 28mm 2 polongan', unit: 'meter', materialPrice: 0, servicePrice: 1760 },
    { code: 'FID-28-3', description: 'Fabric Innerduct diameter 28mm 3 polongan', unit: 'meter', materialPrice: 0, servicePrice: 1760 },
    { code: 'MH-HH1', description: 'Pekerjaan Pembuatan Handhole Type HH1 ukuran dimensi dalam (P X L X T = 170x150x165) cor beton 1 : 2 : 3', unit: 'pcs', materialPrice: 4799000, servicePrice: 2367000 },
    { code: 'MH-HH2', description: 'Pekerjaan Pembuatan Handhole Type HH2 ukuran dimensi dalam (P X L X T = 120x130x165) cor beton 1 : 2 : 3', unit: 'pcs', materialPrice: 3248000, servicePrice: 1830000 },
    { code: 'HH-PIT-P-HA', description: 'Pekerjaan Pembuatan HH Pit Portable Home Access beserta aksesorisnya', unit: 'pcs', materialPrice: 602000, servicePrice: 159800 },
    { code: 'HH-PIT-P-ODP', description: 'Pekerjaan Pembuatan HH Pit Portable ODP beserta aksesorisnya', unit: 'pcs', materialPrice: 1469000, servicePrice: 238400 },
    { code: 'HH-PIT-P-ODC', description: 'Pekerjaan Pembuatan HH Pit Portable ODC beserta aksesorisnya', unit: 'pcs', materialPrice: 6955000, servicePrice: 450000 },
    { code: 'HH-PIT-80', description: 'Pembuatan Handhole Pit ukuran dimensi dalam (P x L x T = 80cm x 80cm x 80cm) cor beton 1 : 2 : 3', unit: 'pcs', materialPrice: 1132000, servicePrice: 596000 },
    { code: 'Slack Support HH', description: 'Pengadaan dan Pemasangan Slack include sabuk ukuran dimensi dalam (P x L = 80cm x 80cm)', unit: 'pcs', materialPrice: 105500, servicePrice: 13610 },
    { code: 'Slack Support Chamber', description: 'Pengadaan dan Pemasangan Slack include sabuk ukuran dimensi dalam (P x L = 120cm x 120cm)', unit: 'pcs', materialPrice: 257800, servicePrice: 33240 },
    { code: 'MH-CA', description: 'Pekerjaan Peninggian Tutup Manhole/Handhole', unit: 'pcs', materialPrice: 671100, servicePrice: 659600 },
    { code: 'CO-OF', description: 'Pekerjaan Cut Over Kabel Serat Optik', unit: 'core', materialPrice: 0, servicePrice: 43780 },
    { code: 'Close Rack 12U', description: '19" Wallmounted Rack 12U Depth 450mm', unit: 'Unit', materialPrice: 0, servicePrice: 550200 },
    { code: 'DC-OF-SM-2A', description: 'Pengadaan dan pemasangan Kabel Serat Optic Penanggal Single Mode 2 core dgn pelindung pipa G 657 A (indoor)', unit: 'meter', materialPrice: 0, servicePrice: 1350 },
    { code: 'FC-SC-DC', description: 'Pengadaan dan pemasangan SC/UPC Connector for Drop / Indoor Cable (Fusion)', unit: 'pcs', materialPrice: 0, servicePrice: 53180 },
    { code: 'Coring', description: 'Pekerjaan bobokan tembok/coring Cor Beton di ruang Shaft', unit: 'titik', materialPrice: 0, servicePrice: 733600 },
    { code: 'Klem Galvanise', description: 'Pengadaan & Pemasangan klem galvanise untuk airblown pipe dengan ketebalan 2mm, lebar 2.5 cm menggunakan dynabolt termasuk rekondisi atau perbaikan kerusakan', unit: 'pcs', materialPrice: 0, servicePrice: 1830 },
    { code: 'Rak Pasif spliter 1:4', description: '19 inch 24 core Pull type optical fiber distribution frame 24 port Rack Mounted Indoor fiber patch panel, Include RS232 Passive Splitter Rackmount Chassis - 2U', unit: 'pcs', materialPrice: 0, servicePrice: 385100 },
    { code: 'Label Kabel Distribusi (KU FO)', description: 'Pengadaan dan Pemasangan label kabel distribusi fo dengan material akrilik warna (P x L = 5cm x 15cm, tebal = 5 mm)', unit: 'pcs', materialPrice: 0, servicePrice: 4590 },
    { code: 'Preliminary Project', description: 'Biaya-biaya yang timbul dalam rangka untuk perijinan dan kompensasi pekerjaan', unit: 'Lumpsum', materialPrice: 0, servicePrice: 0 },
    { code: 'FTM-CR-19', description: 'Pengadaan & Pemasangan Optical Fiber High Density Cable, Close Rack 19 Inch. Lengkap termasuk Fibre Management maximum Capacity 7x144 core / 42U', unit: 'Unit', materialPrice: 0, servicePrice: 334900 },
    { code: 'TC-SM-144', description: 'Pengadaan dan Pemasangan OTB Single Mode kapasitas 144 core (tidak termasuk terminasi), Adapter (SC Connector), pigtail dan protection sleeve pada cassette/box', unit: 'pcs', materialPrice: 0, servicePrice: 83720 },
    { code: 'GC-NYAF-16', description: 'Kabel Grounding NYAF 16 mm', unit: 'meter', materialPrice: 0, servicePrice: 1800 },
    { code: 'BR-HDPE', description: 'Pengadaan dan Pemasangan sistem bracket penopang HDPE dengan bahan plat besi galvanized (elektro) tebal 2 mm ukuran 40x17x4,2 cm (PxTxL) dengan 2 dynabolt stainless steel M10x70mm dan 9 cable ties ukuran 14,5 inch.', unit: 'set', materialPrice: 0, servicePrice: 66020 },
    { code: 'BC-TR-S-0.8', description: 'Penggalian dengan kondisi tanah Padas/Cadas termasuk pengurugan dan perbaikan kembali bekas galian dengan permukaan cor beton 1:2:3 (lebar30cm, ketebalan 40cm) dengan kedalaman minimal 80 cm', unit: 'meter', materialPrice: 130500, servicePrice: 101800 },
    { code: 'BC-TR-S-1', description: 'Penggalian dengan kondisi tanah Padas/Cadas termasuk pengurugan dan perbaikan kembali bekas galian dengan kedalaman minimal 100 cm', unit: 'meter', materialPrice: 0, servicePrice: 121500 },
    { code: 'BC-TR-S-2', description: 'Penggalian dengan kondisi tanah Padas/Cadas termasuk pengurugan dan perbaikan kembali bekas galian dengan kedalaman minimal 120 cm', unit: 'meter', materialPrice: 0, servicePrice: 135900 },
    { code: 'BC-TR-S-3', description: 'Penggalian dengan kondisi tanah Padas/Cadas termasuk pengurugan dan perbaikan kembali bekas galian dengan kedalaman minimal 130 cm', unit: 'meter', materialPrice: 0, servicePrice: 141900 },
    { code: 'BC-TR-S-4', description: 'Penggalian dengan kondisi tanah Padas/Cadas termasuk pengurugan dan perbaikan kembali bekas galian dengan kedalaman minimal 140 cm', unit: 'meter', materialPrice: 0, servicePrice: 145900 },
    { code: 'BC-TR-S-5', description: 'Penggalian dengan kondisi tanah Padas/Cadas termasuk pengurugan dan perbaikan kembali bekas galian dengan kedalaman minimal 150 cm', unit: 'meter', materialPrice: 0, servicePrice: 152800 },
    { code: 'PU-G6.0-35kg', description: 'Pengadaen den Pemasangan Tieng Besl Galvanls 6m tanpa sambungan, berlkut cat dan cor pondesl (1:2:3) dengan kekuetan tank 35kg', unit: 'unit', materialPrice: 0, servicePrice: 158600 },
    { code: 'HS-PS-Exist', description: 'Pengadaan den Pemasangan Slstem Gantung pads tiang ekslsting menggunaken kewet sling baja den klem due lubang', unit: 'meter', materialPrice: 21880, servicePrice: 9310 },
    { code: 'PU-S7.0-400NM', description: 'Pengadaan dan Pemasangan Tiang Besi Telekomunikasi 7 Meter dengan 2 Segmen untuk Kabel Distribusi berikut Cat & Cor Pondasi (1:2:3) dengan Kekuatan Tarik 400 Newton Meter', unit: 'Unit', materialPrice: 0, servicePrice: 197100 },
    { code: 'BC-TR-A-0.4', description: 'Pekerjaan galian pada permukaan jalan aspal yang bebas dari utilitas publik dengan lebar galian 8 cm dan kedalaman 40 cm, termasuk perbaikan, pengurugan (backfilling) menggunakan concrete type K225 dan pengaspalan', unit: 'meter', materialPrice: 0, servicePrice: 164100 },
    { code: 'Tray-Mesh-PVC', description: 'Pengadaan dan pemasangan tray PVC wiring duct 45x65mm yang digunakan untuk jalur penarikan kabel fiber optik', unit: 'meter', materialPrice: 0, servicePrice: 38970 },
    { code: 'BR-L-150-200mm', description: 'Pengadaan dan pemasangan bracket L atau siku panjang 155mm – 200mm', unit: 'Pcs', materialPrice: 0, servicePrice: 10520 },
    { code: 'PU-C7.0-150', description: 'Pengadaan dan Pemasangan Tiang Beton 7 Meter dengan Kekuatan Tarik 150 Kg', unit: 'Unit', materialPrice: 0, servicePrice: 578100 },
    { code: 'PU-C9.0-150', description: 'Pengadaan dan Pemasangan Tiang Beton 9 Meter dengan Kekuatan Tarik 150 Kg', unit: 'Unit', materialPrice: 0, servicePrice: 723600 },
    { code: 'AC-OF-SM-ADSS-12D', description: 'Pengadaan dan Pemasangan Kabel Udara Fiber Optik All Dielectric Self Supporting Cable (ADSS) Single Mode 12 Core G.652.D', unit: 'meter', materialPrice: 0, servicePrice: 3780 },
    { code: 'AC-OF-SM-ADSS-24D', description: 'Pengadaan dan Pemasangan Kabel Udara Fiber Optik All Dielectric Self Supporting Cable (ADSS) Single Mode 24 Core G.652.D', unit: 'meter', materialPrice: 0, servicePrice: 3830 },
    { code: 'AC-OF-SM-ADSS-48D', description: 'Pengadaan dan Pemasangan Kabel Udara Fiber Optik All Dielectric Self Supporting Cable (ADSS) Single Mode 48 Core G.652.D', unit: 'meter', materialPrice: 0, servicePrice: 3850 },
    { code: 'AC-OF-SM-ADSS-96D', description: 'Pengadaan dan Pemasangan Kabel Udara Fiber Optik All Dielectric Self Supporting Cable (ADSS) Single Mode 96 Core G.652.D', unit: 'meter', materialPrice: 0, servicePrice: 4430 },
    { code: 'PU-AS-DE-50/70', description: 'Pengadaan dan Pemasangan Aksesoris Tiang Helical Dead-End Clamp untuk Kabel ADSS ukuran 50/70', unit: 'pcs', materialPrice: 0, servicePrice: 7470 },
    { code: 'PU-AS-SC', description: 'Pengadaan dan Pemasangan Aksesoris Tiang Suspension Clamp Corong untuk Kabel ADSS', unit: 'pcs', materialPrice: 0, servicePrice: 7660 },
    { code: 'PU-AS-HL', description: 'Pengadaan dan Pemasangan Aksesoris Tiang Helical Performed Grip untuk Kabel ADSS', unit: 'pcs', materialPrice: 0, servicePrice: 7750 },
    { code: 'AC-OF-SM-1-3SL', description: 'Pengadaan Dan Pemasangan Drop Cable FO 1 Core Single Mode G.657 dengan Penguat 3 Seling', unit: 'meter', materialPrice: 0, servicePrice: 1430 },
    { code: 'BKR-KU-FO-6-24', description: 'PEMBONGKARAN KABEL UDARA FIBER OPTIK KAPASITAS 6-24 CORE', unit: 'meter', materialPrice: 0, servicePrice: 630 },
    { code: 'BKR-KU-FO-48-96', description: 'PEMBONGKARAN KABEL UDARA FIBER OPTIK KAPASITAS 48-96 CORE', unit: 'meter', materialPrice: 0, servicePrice: 710 },
    { code: 'RGL-KU-FO-6-24', description: 'REGEL KABEL UDARA FIBER OPTIK KAPASITAS 6-24 CORE', unit: 'meter', materialPrice: 0, servicePrice: 530 },
    { code: 'RGL-KU-FO-48-96', description: 'REGEL KABEL UDARA FIBER OPTIK KAPASITAS 48-96 CORE', unit: 'meter', materialPrice: 0, servicePrice: 530 },
    { code: 'PROT-SLV', description: 'PENGADAAN DAN PEMASANGAN PROTECTION SLEEVE 6MM, PANJANG 6CM', unit: 'Pcs', materialPrice: 0, servicePrice: 480 },
    { code: 'T-ROUTE-KABEL', description: 'PEMBUATAN / PEMASANGAN TANDA ROUTE KABEL', unit: 'Unit', materialPrice: 36470, servicePrice: 12060 },
    { code: 'BC-MTR-GALV.2-3.6', description: 'PENGADAAN ALUR KABEL MENGGUNAKAN PIPA GALVANIS DIAMETER 2 INCHI, DI DALAM GALIAN BETON / KERAMIK DENGAN KEDALAMAN 10CM, LEBAR 5CM DARI AREA DISPENSER MENUJU OFFICE TERMASUK PERBAIKAN KEMBALI JALUR GALIAN', unit: 'Mtr', materialPrice: 0, servicePrice: 99080 },
    { code: 'HB-PC-2', description: 'PENGADAAN DAN PEMASANGAN PIPA DUCT DENGAN SYSTEM GANTUNG 2 TIANG BETON, BENTANG S/D 100 METER', unit: 'Mtr', materialPrice: 0, servicePrice: 42790 },
    { code: 'PT-TT-7', description: 'PENGECATAN TIANG TELEPON TUNGGAL 7 M DAN 9 M', unit: 'Btg', materialPrice: 22800, servicePrice: 10900 },
    { code: 'PC-TT-7/9', description: 'PENGECORAN TIANG TELEPON TUNGGAL 7 M DAN 9M', unit: 'Btg', materialPrice: 104300, servicePrice: 50500 },
    { code: 'PU-G6-2,5', description: 'PENGADAAN DAN PEMASANGAN TIANG BESI GALVANIZED MEDIUM DIAMETER 2,5 INCH PANJANG 6 METER, BERIKUT CAT, COR PONDASI ATAU KLEM TUMPUAN KE DINDING TAMBATAN BESERTA MUR MAUT YANG SESUAI LENGKAP', unit: 'Btg', materialPrice: 0, servicePrice: 224700 },
    { code: 'PU-G6-3', description: 'PENGADAAN DAN PEMASANGAN TIANG BESI GALVANIZED MEDIUM DIAMETER 3 INCH PANJANG 6 METER, BERIKUT CAT, COR PONDASI ATAU KLEM TUMPUAN KE DINDING TAMBATAN BESERTA MUR MAUT YANG SESUAI LENGKAP', unit: 'Btg', materialPrice: 0, servicePrice: 224700 },
    { code: 'RP-GJ-1,25', description: 'RISER PIPA 1,25" GALVANIS MEDIUM UTK KABEL TURUN/NAIK CATUAN KT/KU PADA TIANG/DINDING', unit: 'Unit', materialPrice: 0, servicePrice: 32710 },
    { code: 'RP-GJ-1,50', description: 'RISER PIPA 1,50" GALVANIS MEDIUM UTK KABEL TURUN/NAIK CATUAN KT/KU PADA TIANG/DINDING', unit: 'Unit', materialPrice: 0, servicePrice: 38170 },
    { code: 'RP-GJ-2', description: 'RISER PIPA 2,00" GALVANIS MEDIUM UTK KABEL TURUN/NAIK CATUAN KT/KU PADA TIANG/DINDING', unit: 'Unit', materialPrice: 0, servicePrice: 43620 },
    { code: 'S-CLAMP', description: 'S-CLAMP PADA TIANG', unit: 'Bh', materialPrice: 0, servicePrice: 11640 },
    { code: 'SUS-CAP', description: 'SUSPENSION CAPIT', unit: 'Bh', materialPrice: 0, servicePrice: 13580 },
    { code: 'SLACK-SUPP', description: 'PENGADAAN SLACK SUPPORT', unit: 'Pcs', materialPrice: 0, servicePrice: 15520 },
    { code: 'ODP-KLEM-COOKER', description: 'KLEM COOCKER ODP SOLID', unit: 'pcs', materialPrice: 0, servicePrice: 23280 },
    { code: 'ODP-KLEM-KU', description: 'KLEM KABEL UDARA ODP SOLID', unit: 'pcs', materialPrice: 0, servicePrice: 23280 },
    { code: 'ODP-RISE', description: 'RISE PIPE (COOCKER) ODP SOLID', unit: 'Mtr', materialPrice: 0, servicePrice: 1490 },
    { code: 'STAINLESS BELT', description: 'PENGADAAN DAN PEMASANGAN AKSESORIS TIANG BESI STAINLESS BELT', unit: 'pcs', materialPrice: 0, servicePrice: 5540 },
    { code: 'BUCKLE', description: 'PENGADAAN DAN PEMASANGAN AKSESORIS TIANG BESI BUCKLE', unit: 'pcs', materialPrice: 0, servicePrice: 970 },
    { code: 'SUSPENSION AYUN', description: 'PENGADAAN DAN PEMASANGAN AKSESORIS TIANG BESI SUSPENSION AYUN', unit: 'pcs', materialPrice: 0, servicePrice: 13550 },
    { code: 'POLESTRAP SPIRAL', description: 'PENGADAAN DAN PEMASANGAN AKSESORIS TIANG BESI POLESTRAP SPIRAL', unit: 'pcs', materialPrice: 0, servicePrice: 10540 },
    { code: 'ANCHORING', description: 'PENGADAAN DAN PEMASANGAN AKSESORIS TIANG BESI ANCHORING', unit: 'pcs', materialPrice: 0, servicePrice: 14660 },
    { code: 'CLAMP HOOK/BRACKET PELANGGAN SPIRAL', description: 'PENGADAAN DAN PEMASANGAN AKSESORIS TIANG BESI CLAMP HOK/BRACKET PELANGGAN SPIRAL', unit: 'pcs', materialPrice: 0, servicePrice: 11130 },
    { code: 'TRIMBEL', description: 'AKSESORIS TIANG BESI TRIMBEL', unit: 'pcs', materialPrice: 0, servicePrice: 4360 },
    { code: 'SW-BG-3/8"', description: 'SPAN WARTEL DAN BULDOG GRIP 3/8"', unit: 'Bh', materialPrice: 0, servicePrice: 8750 },
    { code: 'SW-BG-5/8"', description: 'SPAN WARTEL DAN BULDOG GRIP 5/8"', unit: 'Bh', materialPrice: 0, servicePrice: 13670 },
    { code: 'PG-2', description: 'PIPA GUIDE DIA 2”', unit: 'Btg', materialPrice: 0, servicePrice: 0 },
    { code: 'G-RING', description: 'RING GUIDE TIANG', unit: 'Bh', materialPrice: 0, servicePrice: 0 },
    { code: 'EC-4-10', description: 'END CAP UKURAN 4-10', unit: 'Bh', materialPrice: 0, servicePrice: 630 },
    { code: 'PP-OF-OUT', description: 'PENGADAAN DAN PEMASANGAN PIPE PROTECTOR OUTDOOR CABLE ( PVC BLACK) HIGH IMPACT CONDUIT 20 MM', unit: 'Mtr', materialPrice: 0, servicePrice: 3570 },
    { code: 'UTP-6', description: 'PENGADAAN DAN PEMASANGAN KABEL UTP CAT 6 PER 1 MTR', unit: 'Mtr', materialPrice: 0, servicePrice: 3490 },
    { code: 'RJ45-CAT6', description: 'PENGADAAN CONNECTOR RJ45 CAT6', unit: 'Pcs', materialPrice: 0, servicePrice: 0 },
    { code: 'TC-IN', description: 'TRAY CABLE MAKSIMAL 10 X 5CM DI SISI OFFICE SESUAI SPACE RUANGAN', unit: 'Mtr', materialPrice: 0, servicePrice: 3490 },
    { code: 'HH-PIT-HA', description: 'PEKERJAAN PEMBUATAN HH PIT HOME ACCESS LENGKAP DENGAN PENUTUP UKURAN DIMENSI DALAM (PXLXT = 40 X 40 X 40 CM) BERTULANG COR BETON 1:2:3 BESERTA AKSESORISNYA', unit: 'Unit', materialPrice: 1122000, servicePrice: 300700 },
    { code: 'HH-PIT-DP', description: 'PEKERJAAN PEMBUATAN HH PIT DP LENGKAP DENGAN PENUTUP UKURAN DIMENSI DALAM (PXLXT = 60 X 40 X 60 CM) BERTULANG COR BETON 1:2:3 BESERTA AKSESORISNYA', unit: 'Unit', materialPrice: 1635000, servicePrice: 339500 },
    { code: 'TTP-MH', description: 'PENGGANTIAN TUTUP MH (95cm x 95 cm) BETON', unit: 'Unit', materialPrice: 1088000, servicePrice: 402500 },
    { code: 'LHR-MH', description: 'PENINGGIAN LEHER MH', unit: 'Unit', materialPrice: 649800, servicePrice: 659600 },
    { code: 'GT-J-HH1-TTP3', description: 'PENGGANTIAN TUTUP HH TYPE 1 TUTUP-3', unit: 'Unit', materialPrice: 1417000, servicePrice: 402500 },
    { code: 'GT-J-HH2-TTP2', description: 'PENGGANTIAN TUTUP HH TYPE 2 TUTUP-2', unit: 'Unit', materialPrice: 2217000, servicePrice: 402500 },
    { code: 'NE-KEY', description: 'PENGGANTIAN KUNCI NODE UKURAN 70MM', unit: 'Node', materialPrice: 0, servicePrice: 20890 },
    { code: 'ODC-BELT', description: 'PEMASANGAN SABUK (70MM X 3MM)', unit: 'Node', materialPrice: 0, servicePrice: 20890 },
    { code: 'ODC-CATKABIJ-NET', description: 'PENGECATAN ULANG KABINET ATAU ODC DAN LABELING', unit: 'm2', materialPrice: 240100, servicePrice: 26670 },
    { code: 'ODC-CATDDKKAB', description: 'PENGECATAN DUDUKAN KABINET', unit: 'm2', materialPrice: 61640, servicePrice: 26670 },
    { code: 'ODC-P-3-IN', description: 'PENGADAAN DAN PEMASANGAN RISER PIPE UNTUK PENGAMAN KABEL OPTIK KE ODC POLE / TITIK NAIK KU DIAMATER 3 INCH PANJANG 3 METER', unit: 'Unit', materialPrice: 0, servicePrice: 56260 },
    { code: 'ODC-P-4-IN', description: 'PENGADAAN DAN PEMASANGAN RISER PIPE UNTUK PENGAMAN KABEL OPTIK KE ODC POLE / TITIK NAIK KU DIAMATER 4 INCH PANJANG 3 METER', unit: 'Unit', materialPrice: 0, servicePrice: 56260 },
    { code: 'ODC-ODP-ADAPT-STDR', description: 'PENGADAAN/PENGGANTIAN ADAPTER SC PADA ODC DAN ODP BAHAN PLASTIK', unit: 'pcs', materialPrice: 0, servicePrice: 1200 },
    { code: 'ODP-KEY', description: 'PENGGANTIAN KUNCI ODP', unit: 'Bh', materialPrice: 0, servicePrice: 10030 },
    { code: 'ODP-SBK', description: 'PENGADAAN DAN PEMASANGAN SABUK ODP', unit: 'Bh', materialPrice: 0, servicePrice: 11640 },
    { code: 'ODP-SOLID-PB-8', description: 'PENGADAAN DAN PEMASANGAN ODP TYPE SOLID KAP 8 CORE ADAPTOR SC/UPC TERDIRI DARI 1 BOX SPLITER (TERMASUK 1 SPLITER 1:8), 1 BOX DUMMY BESERTA ACCESSORIES, BERIKUT PELABELAN DAN PENEMPELAN QR CODE (DISEDIAKAN OLEH TELKOM)', unit: 'Bh', materialPrice: 0, servicePrice: 138000 },
    { code: 'ODP-SOLID-PB-16', description: 'PENGADAAN DAN PEMASANGAN ODP TYPE SOLID KAP 16 CORE ADAPTOR SC/UPC TERDIRI DARI 2 BOX SPLITER (TERMASUK 2 SPLITER 1:8) BESERTA ACCESSORIES, BERIKUT PELABELANDAN PENEMPELAN QR CODE (DISEDIAKAN OLEH TELKOM)', unit: 'Bh', materialPrice: 0, servicePrice: 143300 },
    { code: 'ODP Solid-PB-8 AS', description: 'Pengadaan dan pemasangan ODP type SOLID Kap 8 core adaptor SC/UPC terdiri dari 1 Box Spliter (termasuk 1 spliter 1:8), 1 Box Dummy beserta Accessories, berikut pelabelan dan penempelan QR code (disediakan oleh Telkom). Pemasangan ODP Pole dilengkapi dengan aksesoris instalasi yang terdiri dari 1 buah cooker (PVC 2 inch tipe AW sepanjang 1 meter) dan 2 buah klem (untuk penjepit cooker dan kabel)', unit: 'Bh', materialPrice: 0, servicePrice: 140600 },
    { code: 'ODP Solid-PB-16 AS', description: 'Pengadaan dan pemasangan ODP type SOLID Kap 16 core adaptor SC/UPC terdiri dari 2 Box Spliter (termasuk 2 spliter 1:8), beserta aksesoris ODP, berikut pelabelan dan penempelan QR code (disediakan oleh Telkom). Pemasangan ODP Pole dilengkapi dengan aksesoris instalasi yang terdiri dari 1 buah cooker (PVC 2 inch tipe AW sepanjang 1 meter) dan 2 buah klem (untuk penjepit cooker dan kabel)', unit: 'Bh', materialPrice: 0, servicePrice: 137500 },
    { code: 'DC-PROTEC', description: 'PASANG PELINDUNG LAYANG-LAYANG', unit: 'Rute', materialPrice: 0, servicePrice: 520 },
    { code: 'NE-MS-DUST', description: 'PEMASANGAN DUSH CAP', unit: 'Unit', materialPrice: 0, servicePrice: 30 },
    { code: 'NE-MS-REPL-BATT100', description: 'PENGADAAN DAN PEMASANGAN UNTUK PENGGANTIAN BATERAI 100 AH (TYPE VRLA)', unit: 'Unit', materialPrice: 0, servicePrice: 107900 },
    { code: 'NE-MS-REPL-BATT60', description: 'PENGADAAN DAN PEMASANGAN UNTUK PENGGANTIAN BATERAI 60 AH (TYPE VRLA)', unit: 'Unit', materialPrice: 0, servicePrice: 91950 },
    { code: 'NE-MS-REPL-BATT-45', description: 'PENGADAAN DAN PEMASANGAN UNTUK PENGGANTIAN BATERAI 45 AH (TYPE VRLA)', unit: 'Unit', materialPrice: 0, servicePrice: 91950 },
    { code: 'PIGTAIL', description: 'PEKERJAAN MENYAMBUNGKAN KABEL OPTIK OUTDOOR KE INDOOR) PENGADAAN DAN PEMASANGAN PIGTAIL (SC/FC)', unit: 'Pcs', materialPrice: 0, servicePrice: 54200 },
    { code: 'TRAY-MESH-4', description: 'WIRE MESH CABLE TRAY 40 X 10 CM, DENGAN SUPPORTING MATERIAL', unit: 'Mtr', materialPrice: 0, servicePrice: 41220 },
    { code: 'DC-OF-SJ-655C', description: 'PENGADAAN DAN PEMASANGAN KABEL DUCT FIBER OPTIK SINGLE MODE 144 CORE G 655 C', unit: 'Mtr', materialPrice: 0, servicePrice: 3200 },
    { code: 'PL-RING', description: 'PENGADAAN DAN PEMASANGAN POLE STRAP RING', unit: 'Bh', materialPrice: 0, servicePrice: 11640 },
    { code: 'PL-TYPE-J', description: 'PENGADAAN DAN PEMASANGAN POLE STRAP TYPE J', unit: 'Bh', materialPrice: 0, servicePrice: 11640 },
    { code: 'CASSETTE-FO', description: 'PENGADAAN DAN PEMASANGAN CASSETTE FO BASED TRAY FOR ODC 144/288 CORE PER 12 FIBER TERMASUK ADAPTOR TANPA PIGTAIL', unit: 'pcs', materialPrice: 0, servicePrice: 93240 },
    { code: 'CASSETTE-SPLITTER', description: 'PENGADAAN DAN PEMASANGAN CASSETTE SPLITTER (ODP CA-8)', unit: 'pcs', materialPrice: 0, servicePrice: 0 },
    { code: 'NYY- 3 X 2.5MM', description: '"A. PENGADAAN KABEL LISTRIK NYY 3*2,5MM DARI ACPDB/DCPDB BOX KE MCB BOX \n  B. PENGADAAN NYY 3*2,5MM DARI MCB BOX MENUJU SOCKET POWER UNTUK RACK SERVER\n  C. PENGADAAN NYY 3*2,5MM DARI MCB BOX MENUJU MESIN EDC JIKA DIBUTUHKAN"', unit: 'Mtr', materialPrice: 0, servicePrice: 3490 },
    { code: 'TRAY-BUNDLED-OUT-30', description: 'TRAY CABLE FO CORD BUNDLED OUTDOOR 30X10 CM LENGKAP DENGAN PENGUAT', unit: 'Mtr', materialPrice: 0, servicePrice: 39200 },
    { code: 'TRAY-FEEDER-30', description: 'TRAY CABLE FEEDER OUTDOOR 30X10 CM LENGKAP DENGAN PENGUAT', unit: 'Mtr', materialPrice: 0, servicePrice: 39200 },
    { code: 'TRAY-MESH-2', description: 'WIRE MESH CABLE TRAY 20 X 10 CM, DENGAN SUPPORTING MATERIAL', unit: 'Mtr', materialPrice: 0, servicePrice: 41220 },
    { code: 'TRAY-MESH-3', description: 'WIRE MESH CABLE TRAY 30 X 10 CM, DENGAN SUPPORTING MATERIAL', unit: 'Mtr', materialPrice: 0, servicePrice: 41220 },
    { code: 'VSS-90-2', description: 'VERTICAL SUPPORT STRUCTURE ROD (2M) MAKSIMAL SEPASANG (KIRI-KANAN), DENGAN KIT INSTALASI (TIAP 90CM)', unit: 'Set', materialPrice: 0, servicePrice: 36980 },
    { code: 'PONDASI-TYPE-D500', description: 'PENGADAAN DAN PEMASANGAN PONDASI UNTUK KABINET OUTDOOR BESAR, SIDE WALK DAN PATOK PENGAMAN MENGACU PPJT JARLOKAT DAN SISTEM GROUNDING UNTUK PERANGKAT DAN SEALED MATERIAL (MAX. 1 OHM)', unit: 'Pcs', materialPrice: 4930000, servicePrice: 1443000 },
    { code: 'ADAPT-SPRING', description: 'ADAPTER SPRING', unit: 'Bh', materialPrice: 0, servicePrice: 1200 },
    { code: 'OTP', description: 'PENGADAAN DAN PEMASANGAN OPTICAL TERMINATION POINT 1 CORE', unit: 'Pcs', materialPrice: 0, servicePrice: 7540 },
    { code: 'H-CLAMP', description: 'PENGADAAN DAN PEMASANGAN AKSESORIS TIANG HOSE CLAMP', unit: 'Pcs', materialPrice: 0, servicePrice: 11640 },
    { code: 'DC-SOC', description: 'Pengadaan dan Pemasangan Adaptor Splice On Connector (SOC)', unit: 'pcs', materialPrice: 0, servicePrice: 43210 },
    { code: 'PR-IN-RS', description: 'Pengadaaan dan Pemasangan Precon KSO Indoor Transparant Sudah Termasuk Roset', unit: 'set', materialPrice: 0, servicePrice: 28900 },
    { code: 'BKR-DC', description: 'PEMBONGKARAN DROP CORE', unit: 'Mtr', materialPrice: 0, servicePrice: 270 },
    { code: 'RGL-DC', description: 'REGEL DROP CORE', unit: 'Mtr', materialPrice: 0, servicePrice: 270 },
    { code: 'BKR-RK', description: 'PEMBONGKARAN RUMAH KABEL BERIKUT PATOK PENGAMAN', unit: 'Unit', materialPrice: 0, servicePrice: 136200 },
    { code: 'P-PK-RK', description: 'PERBAIKAN PONDASI DAN KERAMIK YANG RUSAK DI RK', unit: 'Bh', materialPrice: 0, servicePrice: 504400 },
    { code: 'P-KB', description: 'PEMBERSIHAN KABINET TERMASUK MODUL DAN PERKABELAN', unit: 'Bh', materialPrice: 0, servicePrice: 100900 },
    { code: 'PB-TT-7/9', description: 'PEMBONGKARAN, PENGGESERAN DAN PEMASANGAN KEMBALI TIANG BESI 7 M DAN 9 M', unit: 'Btg', materialPrice: 0, servicePrice: 92600 },
    { code: 'MTT-RL-7/9', description: 'MENEGAKKAN TIANG BESI MIRING RUTE LURUS (DW/KU)', unit: 'Btg', materialPrice: 0, servicePrice: 20200 },
    { code: 'MTT-RS-7/9', description: 'MENEGAKKAN TIANG BESI MIRING RUTE SUDUT (DW/KU)', unit: 'Btg', materialPrice: 0, servicePrice: 25290 },
    { code: 'PT-TUNJANG', description: 'PEMASANGAN TEMBERANG TUNJANG', unit: 'Unit', materialPrice: 0, servicePrice: 103500 },
    { code: 'EC-26-52', description: 'END CAP UKURAN 26-52', unit: 'Bh', materialPrice: 0, servicePrice: 1610 },
    { code: 'P-J-H1/H2', description: 'PEMBERSIHAN MANHOLE H1/H2', unit: 'Bh', materialPrice: 0, servicePrice: 245200 },
    { code: 'P-J-H3/H4', description: 'PEMBERSIHAN MANHOLE H3/H4', unit: 'Bh', materialPrice: 0, servicePrice: 337800 },
    { code: 'P-H-1', description: 'PEMBERSIHAN HANHOLE TYPE 1 (120 cm x 100 cm x 160 cm)', unit: 'Bh', materialPrice: 0, servicePrice: 43620 },
    { code: 'P-H-2', description: 'PEMBERSIHAN HANHOLE TYPE 2 (180 cm x 100 cm x 160 cm )', unit: 'Bh', materialPrice: 0, servicePrice: 54530 },
    { code: 'RK-LY', description: 'PEREMAJAAN/UPDATE LAYOUT KABINET', unit: 'Bh', materialPrice: 0, servicePrice: 9650 },
    { code: 'RK-PATOK', description: 'PERBAIKAN PATOK BERIKUT CAT ULANG', unit: 'Bh', materialPrice: 0, servicePrice: 138000 },
    { code: 'RK-DUDUKKAB', description: 'PERBAIKAN BETON DUDUKAN KABINET', unit: 'm3', materialPrice: 0, servicePrice: 581800 },
    { code: 'RK-GRD', description: 'PEMELIHARAAN/PENGUKURAN GROUNDING RK/NODE', unit: 'Bh', materialPrice: 0, servicePrice: 35370 },
    { code: 'NE-KOORD', description: 'MENGUKUR KOORDINAT NETWORK ELEMENT DAN MENYERAHKANNYA KE TELKOM', unit: 'Bh', materialPrice: 0, servicePrice: 10760 },
    { code: 'DP-CLEAN', description: 'PEMELIHARAAN/PERAPIHAN/PEMBERSIHAN LUAR-DALAM', unit: 'Set', materialPrice: 0, servicePrice: 10240 },
    { code: 'DP-GRD', description: 'PEMELIHARAAN & PENGUKURAN GROUNDING', unit: 'Bh', materialPrice: 0, servicePrice: 35370 },
    { code: 'DP-LAB', description: 'PELABELAN', unit: 'Set', materialPrice: 0, servicePrice: 4860 },
    { code: 'DP-IDLE', description: 'PEMBONGKARAN DP IDLE', unit: 'Bh', materialPrice: 0, servicePrice: 12020 },
    { code: 'DP-MOVING', description: 'PENGALIHAN DP (KE TIANG YG LAIN)', unit: 'Bh', materialPrice: 0, servicePrice: 30070 },
    { code: 'DP-TIANG', description: 'PENGECATAN BRANDING TIANG WARNA MERAH SILVER', unit: 'Btg', materialPrice: 0, servicePrice: 16720 },
    { code: 'DW-JOINT', description: 'PEMBENAHAN SAMBUNGAN DW', unit: 'Bh', materialPrice: 0, servicePrice: 9390 },
    { code: 'FTM-LY', description: 'PEREMAJAAN/UPDATE LAYOUT KABINET', unit: 'unit', materialPrice: 0, servicePrice: 9650 },
    { code: 'FTM-LAB', description: 'PELABELAN CORE', unit: 'Core', materialPrice: 0, servicePrice: 2200 },
    { code: 'FTM-MSR-CORE', description: 'PENGUKURAN CORE', unit: 'Core', materialPrice: 0, servicePrice: 14160 },
    { code: 'FTM-GRD', description: 'PEMELIHARAAN/PENGUKURAN GROUNDING NODE', unit: 'Titik', materialPrice: 0, servicePrice: 35370 },
    { code: 'NE-LOG', description: 'MELENGKAPI LOGBOOK NODE NETWORK ELEMENT', unit: 'Node', materialPrice: 0, servicePrice: 9650 },
    { code: 'FTM-PC', description: 'PERAPIHAN PATCH CORE', unit: 'pcs', materialPrice: 0, servicePrice: 2410 },
    { code: 'FTM-CLEAN', description: 'PEMBERSIHAN RAK FTM DAN TRAY CABLE', unit: 'unit', materialPrice: 0, servicePrice: 14480 },
    { code: 'FTM-VA-PORT', description: 'VALIDASI PORT FTM', unit: 'Port', materialPrice: 0, servicePrice: 8970 },
    { code: 'FTM-LABEL', description: 'PEKERJAAN LABEL RACK DAN SUBRACK FTM (REVITALISASI)', unit: 'pcs', materialPrice: 0, servicePrice: 1000 },
    { code: 'ODC-LY', description: 'PEREMAJAAN/UPDATE LAYOUT KABINET', unit: 'Node', materialPrice: 0, servicePrice: 9650 },
    { code: 'ODC-LAB', description: 'PELABELAN CORE', unit: 'Core', materialPrice: 0, servicePrice: 2200 },
    { code: 'ODC-MSR-CORE', description: 'PENGUKURAN CORE', unit: 'Core', materialPrice: 0, servicePrice: 14160 },
    { code: 'ODC-GRD', description: 'PEMELIHARAAN/PENGUKURAN GROUNDING NODE', unit: 'Titik', materialPrice: 0, servicePrice: 35370 },
    { code: 'ODC-SPLT', description: 'PENGECEKAN DAN PEMELIHARAAN SPLITTER', unit: 'Unit', materialPrice: 0, servicePrice: 10240 },
    { code: 'ODC-PC', description: 'PERAPIHAN PATCH CORE', unit: 'pcs', materialPrice: 0, servicePrice: 2410 },
    { code: 'ODC-REP', description: 'PENGGANTIAN ODC KONVENSIONAL DENGAN ODC SPLINTER', unit: 'Unit', materialPrice: 0, servicePrice: 2425000 },
    { code: 'ODC-VA-PORT', description: 'VALIDASI PORT ODC', unit: 'Port', materialPrice: 0, servicePrice: 8970 },
    { code: 'ODC-PP', description: 'PEMBONGKARAN ODC KAP 144-288 BERIKUT PATOK PENGAMAN', unit: 'Set', materialPrice: 0, servicePrice: 3298000 },
    { code: 'G-ODC-C-48', description: 'PENGGESERAN ODC-POLE (OUTDOOR) KAP 48 CORE (PEMBONGKARAN DAN PEMASANGAN KEMBALI TANPA MERUBAH ATAU MENGGANTI ALPRO) tidak termasuk penyambungan kabel', unit: 'Pcs', materialPrice: 0, servicePrice: 7150000 },
    { code: 'G-ODC-C-144', description: 'PENGGESERAN KABINET ODC (OUTDOOR) KAP 144 CORE (PEMBONGKARAN DAN PEMASANGAN KEMBALI TANPA MERUBAH ATAU MENGGANTI ALPRO) tidak termasuk penyambungan kabel', unit: 'Pcs', materialPrice: 0, servicePrice: 8503000 },
    { code: 'G-ODC-C-288', description: 'PENGGESERAN KABINET ODC (OUTDOOR) KAP 288 CORE (PEMBONGKARAN DAN PEMASANGAN KEMBALI TANPA MERUBAH ATAU MENGGANTI ALPRO) tidak termasuk penyambungan kabel', unit: 'Pcs', materialPrice: 0, servicePrice: 8543000 },
    { code: 'ODP-CLEAN', description: 'PEMELIHARAAN/PERAPIHAN/PEMBERSIHAN/(CAT UTK DOME) LUAR-DALAM', unit: 'Unit', materialPrice: 0, servicePrice: 10240 },
    { code: 'ODP-GRD', description: 'PEMELIHARAAN & PENGUKURAN GROUNDING', unit: 'Unit', materialPrice: 0, servicePrice: 35370 },
    { code: 'ODP-LAB', description: 'PELABELAN NAMA ODP', unit: 'Unit', materialPrice: 0, servicePrice: 4860 },
    { code: 'ODP-TERM', description: 'PERAPIHAN TERMINASI ODP', unit: 'Unit', materialPrice: 0, servicePrice: 2410 },
    { code: 'ODP-SPL', description: 'PENGECEKAN DAN PEMELIHARAAN SPLITTER', unit: 'Unit', materialPrice: 0, servicePrice: 10240 },
    { code: 'ODP-TIANG', description: 'PENGECATAN BRANDING TIANG WARNA MERAH SILVER', unit: 'Btg', materialPrice: 0, servicePrice: 16720 },
    { code: 'ODP-LABEL', description: 'RE-LABELING ODP', unit: 'Node', materialPrice: 0, servicePrice: 4860 },
    { code: 'ODP-VA-PORT', description: 'VALIDASI PORT ODP', unit: 'Port', materialPrice: 0, servicePrice: 8970 },
    { code: 'ODP-LBL-CORE', description: 'PELABELAN DROP CORE DI PORT SPLITTER', unit: 'Core', materialPrice: 0, servicePrice: 4860 },
    { code: 'G-ODP-CA-8', description: 'PENGGESERAN ODP TYPE CLOSURE AERIAL KAP 8 CORE (TANPA MERUBAH ATAU MENGGANTI ALPRO)', unit: 'Pcs', materialPrice: 0, servicePrice: 252200 },
    { code: 'G-ODP-CA-16', description: 'PENGGESERAN ODP TYPE CLOSURE AERIAL KAP 16 CORE (TANPA MERUBAH ATAU MENGGANTI ALPRO)', unit: 'Pcs', materialPrice: 0, servicePrice: 252200 },
    { code: 'G-ODP-A-8', description: 'PENGGESERAN ODP TYPE INDOOR/WALL KAP 8 CORE (TANPA MERUBAH ATAU MENGGANTI ALPRO)', unit: 'Pcs', materialPrice: 0, servicePrice: 252200 },
    { code: 'G-ODP-A-16', description: 'PENGGESERAN ODP TYPE INDOOR/WALL KAP 16 CORE (TANPA MERUBAH ATAU MENGGANTI ALPRO)', unit: 'Pcs', materialPrice: 0, servicePrice: 252200 },
    { code: 'G-ODP-PB-8', description: 'PENGGESERAN ODP TYPE OUTDOOR/WALL DAN POLE KAP 8 CORE (TANPA MERUBAH ATAU MENGGANTI ALPRO)', unit: 'Pcs', materialPrice: 0, servicePrice: 252200 },
    { code: 'G-ODP-PB-16', description: 'PENGGESERAN ODP TYPE OUTDOOR/WALL DAN POLE KAP 16 CORE (TANPA MERUBAH ATAU MENGGANTI ALPRO)', unit: 'Pcs', materialPrice: 0, servicePrice: 252200 },
    { code: 'G-ODP-SOLID-PB-8', description: 'PENGGESERAN ODP TYPE SOLID KAP 8 CORE (TANPA MERUBAH ATAU MENGGANTI ALPRO)', unit: 'Pcs', materialPrice: 0, servicePrice: 252200 },
    { code: 'G-ODP-SOLID-PB-16', description: 'PENGGESERAN ODP TYPE SOLID KAP 16 CORE (TANPA MERUBAH ATAU MENGGANTI ALPRO)', unit: 'Pcs', materialPrice: 0, servicePrice: 252200 },
    { code: 'G-ODP-PL-8', description: 'PENGGESERAN ODP ( PILAR ) KAP 8 CORE TERMASUK PIGTAIL (PEMBONGKARAN DAN PEMASANGAN KEMBALI TANPA MERUBAH ATAU MENGGANTI ALPRO)', unit: 'Pcs', materialPrice: 0, servicePrice: 252200 },
    { code: 'G-ODP-PL-16', description: 'PENGGESERAN ODP ( PILAR ) KAP 16 CORE TERMASUK PIGTAIL (PEMBONGKARAN DAN PEMASANGAN KEMBALI TANPA MERUBAH ATAU MENGGANTI ALPRO)', unit: 'Pcs', materialPrice: 0, servicePrice: 252200 },
    { code: 'DC-SBG', description: 'PENYAMBUNGAN DROP CABLE FO SINGLE MODE KAP 1 CORE DENGAN CARA FUSION SPLICE TERMASUK HEAT-STRINK', unit: 'Core', materialPrice: 0, servicePrice: 46190 },
    { code: 'NE-MS-LAB', description: 'PELABELAN CORE', unit: 'Core', materialPrice: 0, servicePrice: 2200 },
    { code: 'NE-MS-GRD', description: 'PEMELIHARAAN/PENGUKURAN GROUNDING NODE', unit: 'Titik', materialPrice: 0, servicePrice: 35370 },
    { code: 'NE-MS-PC', description: 'PERAPIHAN PATCH CORE', unit: 'Mtr', materialPrice: 0, servicePrice: 2410 },
    { code: 'NE-MS-RECT', description: 'PENGUKURAN DAN PEMELIHARAAN RECTIFIER', unit: 'Set', materialPrice: 0, servicePrice: 29250 },
    { code: 'NE-MS-FAN', description: 'PEMBERSIHAN DAN PENGECEKAN FAN/KIPAS', unit: 'Unit', materialPrice: 0, servicePrice: 10240 },
    { code: 'NE-MS-ALARM', description: 'PENGECEKAN ALARM', unit: 'Set', materialPrice: 0, servicePrice: 9650 },
    { code: 'NE-MS-TEMP', description: 'PENGECEKAN SUHU DAN KELEMBABAN KABINET', unit: 'Node', materialPrice: 0, servicePrice: 9650 },
    { code: 'NE-MS-BATT', description: 'PENGUKURAN DAN PEMELIHARAAN BATERAI', unit: 'Bank', materialPrice: 0, servicePrice: 37610 },
    { code: 'NE-MS-CD', description: 'PENGUKURAN CATU DAYA PLN DAN KWH METER SERTA VALIDASI TOKEN', unit: 'Node', materialPrice: 0, servicePrice: 29250 },
    { code: 'NE-MS-MODDELV', description: 'PENGIRIMAN DAN PENGAMBILAN MODULE PERANGKAT AKTIF YG RUSAK/TERGANGGU DARI WAREHOUSE KE LOKASI GANGGUAN DAN SEBALIKNYA TANPA MELAKSANAKAN KEGIATAN LOGIC', unit: 'Unit', materialPrice: 0, servicePrice: 79410 },
    { code: 'NE-MS-GENSET', description: 'MEMBAWA,MENGHIDUPKAN DAN MANJAGA OPERASIONAL GENSET SAAT PLN MATI,DAN MEMBAWA KEMBALI GENSET SAAT PLN NORMAL DI KEMBALIKAN KE TEMPAT PENYIMPANAN SEMULA', unit: 'Unit', materialPrice: 0, servicePrice: 125300 },
    { code: 'NE-MS-RECT-REP', description: 'PEMASANGAN RECTIFIER NE AKSES EKSISTING', unit: 'Unit', materialPrice: 0, servicePrice: 210900 },
    { code: 'NE-MS-ISNT', description: 'PENGECEKAN DAN PENGUATAN BAUT DALAM PERANGKAT', unit: 'Unit', materialPrice: 0, servicePrice: 10250 },
    { code: 'NE-MS-BKR', description: 'PEKERJAAN PEMBONGKARAN PERANGKAT AKTIF (MSAN, OAN, ONU, RDSLAM) BESERTA PATOK PENGAMAN DAN PERAPIHAN KEMBALI LOKASI BEKAS PEMBONGKARAN', unit: 'Unit', materialPrice: 0, servicePrice: 3298000 },
    { code: 'DISMANTLING-MDU', description: 'DISMANTLING MDU DAN ASSESORIESNYA, CHECKLIST PENDATAAN, DAN REKONDISI EKS LOKASI BONGKARAN MDU', unit: 'Ls', materialPrice: 0, servicePrice: 2886000 },
    { code: 'FAL-LOC', description: 'PEKERJAAN PENCARIAN TITIK KABEL PUTUS PADA SAAT PERBAIKAN GANGGUAN MENGGUNAKAN ALAT TAMBAHAN RADIO DETECTOR', unit: 'titik', materialPrice: 0, servicePrice: 86330 },
    { code: 'WSM-PHK3', description: 'PEKERJAAN PENGAWASAN DAN PENGAMANAN UNTUK PROJECT PIHAK KETIGA (INSTALASI LAIN) YANG BERPOTENSI MEMBERIKAN DAMPAK GANGGUAN PADA ALPRO TELKOM', unit: 'Mandays', materialPrice: 0, servicePrice: 156400 },
    { code: 'DIS-ODP', description: 'PEMBONGKARAN ODP BESERTA ASESORISNYA DAN JASA PEMBAWAAN KE GUDANG TELKOM', unit: 'Pcs', materialPrice: 0, servicePrice: 12020 },
    { code: 'RENT-IBT', description: 'Biaya-biaya yang timbul dalam rangka sewa lahan untuk penempatan Alpro Telkom di polongan atau lahan pihak ketiga', unit: 'Lumpsum', materialPrice: 0, servicePrice: 0 },
    { code: 'RENT-BMN', description: 'Biaya-biaya yang timbul dalam rangka sewa lahan untuk penempatan Alpro Telkom di lahan milik negara', unit: 'Lumpsum', materialPrice: 0, servicePrice: 0 },
    { code: 'PU-W7', description: 'Pengadaan dan Pemasangan Tiang Kayu Keras setara ULIN panjang 7 meter tebal 8 cm x 8 cm Full (modifikasi sambungan dengan system klem kayu + mur baut), berikut cat, cor pondasi atau kayu klem tumpuan ke dinding tambatan menggunakan kayu beserta mur baut yang sesuai lengkap dengan assesories', unit: 'Btg', materialPrice: 0, servicePrice: 222200 }
];
